### ISSUE TITLE
Error reported when processing swagger of DataFactory which has enum with object type

### ISSUE THREAD

**Issue by RodgeFu** [Azure/autorest.modelerfour#102]
As shown below:

![image](https://user-images.githubusercontent.com/6038235/71523009-0e036b80-2902-11ea-9446-685e019a1ea5.png)

**Comment by weidongxu-microsoft** [comment]
Saw this in GraphRBAC as well. It's more like an existing error on Swagger (type=object, then x-ms-enum modelAsString=true, quite a conflict). I think latest Swagger Validator would forbidden this. But older ones exist.

**Comment by RodgeFu** [comment]
I am afraid we will not be able to fix the issue for all the existing ones in swagger. It will be helpful if modelerfour can handle it like v1. @fearthecowboy , will this be handled in modelerfour?

**Comment by fearthecowboy** [comment]
DataFactory provides some very bad patterns that I'm not sure we can support. 

`type:object` and `modelAsString:true` is just plain wrong.  We're not going to carry forward bad code and expect something valid. If they want it to work with V3 generators, they're going to have to fix the input. 

Handling of `enum` values is predicated on them being constant values in the end, and calling it an object and expecting to support an enum for that is just not going to work.

**Comment by fearthecowboy** [comment]
I'm updating the modelerfour to return a better error, but we're not going to support `object` enums.
