### ISSUE TITLE
Provide indication in the code model what context schema is used in

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest.modelerfour#103]
Input/output
XML/Json

Useful to decide what serializers/deserializers need to be generated.

**Comment by fearthecowboy** [comment]
The body parameter does have the knownMediaType (json/xml/form) that the body is expected to be in. 

Input/output is duplicated with #23

**Comment by pakrym** [comment]
> The body parameter does have the knownMediaType (json/xml/form) that the body is expected to be in.

Can we add knownMediaType to all the schemas?

**Comment by fearthecowboy** [comment]
You want to know if a given model could ever be asked to be be serialized or deserialized to a specific format? 

That's so you don't have to generate serialization code for a given model + format when it's never programmatically possible? 

I can see why that'd be useful.

**Yes**, I've added that to #23.
