### ISSUE TITLE
Double-check if override-client-name is correctly supported

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.modelerfour#104]
Maybe we can close the issue right now, but want to double check first :)

**Comment by lmazuel** [comment]
Called with `--override-client-name=FooOverride` and didn't find it in the codemodel.

**Comment by fearthecowboy** [comment]
Whoa, I didn't even know that was there.  Definitely a bug.

**Comment by fearthecowboy** [comment]
Did this *ever* work? I can't find *any* code that even handles that. 

oooooh. I think it was handled in the modeler.  (which wouldn't be in the autorest code base)

I've put it into the modelerfour.   #128 

Curious tho' -- I've always used `--title:XXX` on the cmdline to accomplish the same thing.

**Comment by fearthecowboy** [comment]
Try `4.3.134` +

**Comment by lmazuel** [comment]
confirmed with 4.3.142
