### ISSUE TITLE
Consider supporting x-ms-client-name on schemas

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest.modelerfour#105]
It's something we do a lot in storage:

https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage/Azure.Storage.Blobs/swagger#restypeservicecompproperties

**Comment by fearthecowboy** [comment]
and make sure it works with XML by adding name to XML extensions when it's there.

**Comment by fearthecowboy** [comment]
`x-ms-client-name` shouldn't affect xml serialization -- the `serialization` node in `ObjectSchema` indicates only wire-format information and not the generated client name. 

(which means that the generated class should still use `language.default.name` for the member name.
