### ISSUE TITLE
x-ms-client-flatten missing in yaml in some cases

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest.modelerfour#107]
modelerfour version: 4.2.99 (which does not include flattener plugin)
core version: 3.0.6182

Input
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Resources/stable/2019-08-01/resources.json#L5301

YAML from modelerfour miss the "x-ms-client-flatten" under WhatIfOperationResult properties,
[resources-yaml.txt](https://github.com/Azure/autorest.modelerfour/files/4024429/resources-yaml.txt)

This bug appears to depend on something else. I can see "x-ms-client-flatten" extension with YAML from https://github.com/Azure/autorest.testserver/blob/master/swagger/model-flattening.json

**Comment by fearthecowboy** [comment]
If you are using the flattener by having flatten-models / flatten-parameters (see https://github.com/Azure/autorest.modelerfour/tree/master/modelerfour#modelfour-options) 
you should be never getting them now.

if you're not enabling them, it shouldn't be removing them from the model now.

try `4.3.131`+ to try that out

**Comment by weidongxu-microsoft** [comment]
Yes, it is fixed. Thanks.
