### ISSUE TITLE
x-ms-parameter-location

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.modelerfour#11]
If value is "method", just bring it into each operation directly.
If value is "client", make it available at the main level.

For multi-api, if some Swagger says "method" and some says "client", I suggest to fail. I feel we have full control over the semantic of multiapi and our own x-ms things, so we can afford that

**Comment by fearthecowboy** [comment]
Parameters have `implementation` property -- `Method` or `Client`

(ie https://github.com/Azure/autorest.modelerfour/blob/master/modelerfour/test/outputs/body-datetime-rfc1123/code-model-v4.yaml#L309 )

**Comment by lmazuel** [comment]
Saw them indeed, thanks!
