### ISSUE TITLE
x-ms-client-name missing

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.modelerfour#114]
In Storage Swagger:
https://github.com/Azure/azure-rest-api-specs/blob/12ff3b96ec4ede0a56a7315bcdaefe9ae8aa9168/specification/storage/data-plane/Microsoft.BlobStorage/preview/2019-02-02/blob.json#L9008-L9018

![image](https://user-images.githubusercontent.com/1050156/72374805-d34e5100-36bf-11ea-9d19-2c191f4a7bc5.png)

m4 106

**Comment by fearthecowboy** [comment]
Found another place where it's needed to be handled. 

Try `4.2.110`

**Comment by lmazuel** [comment]
Fixed
