### ISSUE TITLE
when enum type has only one value in swagger, it becomes constants in code model v4, when it has more than one values, it becomes seated-choices

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.modelerfour#116]
This is the original swagger type definition
![image](https://user-images.githubusercontent.com/55688292/72399743-035e2880-3782-11ea-9ee1-3d66f7940bd3.png)
as you can see the Kind is enum. it has only one value 
but in the codemodel file，the kind type is ref_43 which is constants
![image](https://user-images.githubusercontent.com/55688292/72400000-ccd4dd80-3782-11ea-8f8d-b37cfbb53eae.png)

when I add a enum value into the Kind type like this 
![image](https://user-images.githubusercontent.com/55688292/72402249-9cdd0880-3789-11ea-9067-86ea37ca6152.png)

the codemodel v4 becomes sealed-choices type
![image](https://user-images.githubusercontent.com/55688292/72402295-c39b3f00-3789-11ea-9ad8-bf3b7ded041f.png)

I think the sealed-choice means enum but it failed to change it that way when swagger enum only has single value.

I am using managednetwork swagger file as input

**Comment by fearthecowboy** [comment]
Yes, `ChoiceSchema`/`SealedChoiceSchema` are Enums 

`SealedChoiceSchema` represents an enum that will *never* accept a different value. Not expandable, not ever.
`ChoiceSchema` is an enum that may one day have additional values (so the API should tolerate that)

If an enum only has a single value, we treat that as a constant. (If there is only one possible value, then that must be the value)

Although, if `modelAsString` is true, that should be a `ChoiceSchema` .  I can check on that.

**Comment by qiaozha** [comment]
Thank you. but how do we know that an enum is expandable or not from swagger definition?

**Comment by fearthecowboy** [comment]
`x-ms-enum.modelAsString: true` tells us that it's expandable.
