### ISSUE TITLE
Payload flattening doesn't take into account hierarchy.

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.modelerfour#121]
Example with this Swagger:
https://github.com/Azure/autorest.testserver/blob/53057ff481de523f3c40f1a2bb7035f0d4e606fb/swagger/storage.json#L426-L440

Once flattening applied, `StorageAccountCreateParameters` has one parameter `account_type` + allOf Resource.

Payload flattening should not apply, since the sum of attributes from the allOf are greater than the threshold I gave to autorest

```
version: 3.0.6185
use-extension:
  "@autorest/modelerfour": "4.3.121"
```
autorest-beta 3.0.6149

**Comment by fearthecowboy** [comment]
Should be better in `4.3.127`

**Comment by lmazuel** [comment]
confirmed in 4.3.142
