### ISSUE TITLE
Missing flattening

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.modelerfour#125]
https://github.com/Azure/autorest.testserver/blob/53057ff481de523f3c40f1a2bb7035f0d4e606fb/swagger/body-string.json#L362

This one used to be flattened with v2, and is not anymore with m4 127.

Looking at the Swagger, it seems fair to flatten it

**Comment by fearthecowboy** [comment]
I'm confused -- is this not flattened for you?

https://github.com/Azure/autorest.modelerfour/blob/4d1d85a80a9ed6793ece8e1bab07f2f927efb653/modelerfour/test/scenarios/body-string/flattened.yaml#L1264-L1301

**Comment by lmazuel** [comment]
Hum, my generated code was not flatten, let me re-check

**Comment by fearthecowboy** [comment]
added a check to not count constants in the threshold calculation. #130

**Comment by fearthecowboy** [comment]
try 4.3.142

**Comment by lmazuel** [comment]
Worked :)
