### ISSUE TITLE
Problems generating GraphRBAC swagger

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest.modelerfour#132]
Throws "FATAL: Error: Enum types of 'undefined' and format 'undefined' are not supported. Correct your input (GroupMembershipClaimTypes)." regarding [this enum](https://github.com/Azure/azure-rest-api-specs/blob/398b5e076eea01f76b208ef27832a1989da2f494/specification/graphrbac/data-plane/Microsoft.GraphRbac/stable/1.6/graphrbac.json#L2839). 

These are the settings I have:
input-file: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/graphrbac/data-plane/Microsoft.GraphRbac/stable/1.6/graphrbac.json
output-folder: _generated
package-name: azure-graphrbac
namespace: azure.graphrbac
no-namespace-folders: true
license-header: MICROSOFT_MIT_NO_VERSION
payload-flattening-threshold: 2
package-version: 0.61.1

**Comment by fearthecowboy** [comment]
Sorry, not going to address this in code. It's gotta be fixed in the swagger (type:string)
