### ISSUE TITLE
Issues generating 20190-06-01 blob azure-mgmt-storage swagger

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest.modelerfour#133]
Output from failed call:
AutoRest code generation utility [version: 3.0.6149; node: v10.16.0, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\iscai\.autorest\@autorest_core@3.0.6187\node_modules\@autorest\core\dist' (3.0.6187)
   Loading local AutoRest extension '@autorest/python' (F:\autorest.python)
   Loading AutoRest extension '@autorest/modelerfour' (4.3.142->4.3.142)

ERROR: Schema violation: Missing required property: paths
    - https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/storage/resource-manager/Microsoft.Storage/stable/2019-06-01/common.json:1:1
ERROR: Schema violation: Missing required property: paths
    - https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/storage/resource-manager/Microsoft.Storage/stable/2019-06-01/common.json:1:1
Process() cancelled due to failure

Using this readme to call autorest-beta: https://github.com/Azure/autorest.python/blob/4a8d190bc1b611b4b110db83ad32748392b2b4b3/test/services/azure-mgmt-storage/README.md

**Comment by fearthecowboy** [comment]
fixed in .144 and core 3.0.6198

**Comment by lmazuel** [comment]
fixed indeed
