### ISSUE TITLE
Some description missing text is replaced with empty string (or other text)

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.modelerfour#136]
So, in the latest M4 (), some of the 'missing description' text is now an empty string:
![image](https://user-images.githubusercontent.com/17788297/73028477-756de780-3dea-11ea-9b9a-37830073bd96.png)

I would have thought this intentional if ALL descriptions with no text became empty strings, but only some of it did. I don't know if it was related to working on https://github.com/Azure/autorest.modelerfour/issues/30. This is breaking for us because our csproj says if there are warnings, they count as errors. And when XML comment parameter descriptions are missing, that is a warning.

Additionally, it seems that all the descriptions for the ChoiceSchema end up like this:
![image](https://user-images.githubusercontent.com/17788297/73030429-7d2f8b00-3dee-11ea-8412-4e119de91c03.png)

**Comment by fearthecowboy** [comment]
Well, I'm cleaning out the places I have descriptions that are the `MISSING*` strings; if they don't have a description, you should be getting an empty string. 

The `The value 'undefined'` is clearly not correct tho'

**Comment by fearthecowboy** [comment]
The descriptions with 'undefined' are fixed.

The empty string for empty descriptions is 'as-designed' (so you'll have to check for empty text when generating doc comments)

**Comment by MiYanni** [comment]
Fixed.
