### ISSUE TITLE
Modeler should flatten for us

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.modelerfour#14]
Should the modeler flatten for us?

**Comment by fearthecowboy** [comment]
I've been thinking about this. 

I can create a flattener plugin which would do that, similar to how we did it before, which isn't too bad.

**Comment by lmazuel** [comment]
Closing, since we have it now. Create bug to reference troubles instead
https://github.com/Azure/autorest.modelerfour/issues/122
https://github.com/Azure/autorest.modelerfour/issues/121

**Comment by lmazuel** [comment]
From @fearthecowboy 

> Flattening support is in 4.3.121+
>  
> you'll need to opt-in to it's behavior by putting 
> 
> modelerfour:
>   flatten-models: true
>   flatten-payloads: true
> 
> in your extension configuration
>  
> --payload-flattening-threshold on the command line works
> x-ms-payload-flattening-threshold on the operation works (so it can be handled per-operation)
>  
> It still leaves (unused) flattened schemas in the model -- I'm waiting for a fix from david before I add the code to trim them.
>  
> --recursive-payload-flattening can be specified to do the nested parameter flattening like powershell uses
