### ISSUE TITLE
Model flattening misses allOf properties

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.modelerfour#140]
**Description**
The test server has an explicit test for this. Basically, a property that gets flattened into the schema it is part of misses the properties of that class's `allOf`. So, in the case here, when `max_product_image` gets flattened, you only end up with the immediate property `@odata.value` and you do not get the `generic_value` property. You should have both properties in the schema that the property was part of. The test on the test server is `putModelFlattenCustomBase`.
![image](https://user-images.githubusercontent.com/17788297/73212435-1a4a3680-4103-11ea-9a95-e5a23b8fd7ec.png)

**ModelerFour**: 4.3.144
**AutoRest-core**: 3.0.6198
**OpenAPI/Swagger file**: model-flattening.json (from test server)

**Comment by fearthecowboy** [comment]
4.4.156 should fix this?

**Comment by jianghaolu** [comment]
I confirm this is working now in 4.4.158. But payload flattening has a similar issue:

```json
"BaseProduct": {
      "type":  "object",
      "description": "The product documentation.",
      "required": [
        "base_product_id"
      ],
      "properties": {
        "base_product_id": {
          "type": "string",
          "description": "Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles.",
          "x-ms-client-name": "productId"
        },
        "base_product_description": {
          "type": "string",
          "description": "Description of product.",
          "x-ms-client-name": "description"
        }
      },
      "example": {
        "name": "Puma",
        "id": 1
      }
    },
    "SimpleProduct": {
      "type":  "object",
      "description": "The product documentation.",
      "allOf": [ { "$ref": "#/definitions/BaseProduct" } ],
      "properties": {
        "details": {
          "x-ms-client-flatten": true,
          "$ref": "#/definitions/SimpleProductProperties"
        }
      }
    },
```

In generated code, we have
```java
    public Mono<SimpleResponse<SimpleProduct>> postFlattenedSimpleProductWithResponseAsync(String maxProductDisplayName, String genericValue, String odataValue) {
```

where the product id is missing from the parameters.

**Comment by lmazuel** [comment]
Confirmed with @jianghaolu for Java and works for Python
