### ISSUE TITLE
Flattened parameter "language/default/name" doesn't match their property counterpart

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.modelerfour#144]
Example with "odatavalue":
https://github.com/Azure/autorest.testserver/blob/db336be702f88f1f285fce9e3ad6898eb0f9d8fa/swagger/model-flattening.json#L546

The property is:
![image](https://user-images.githubusercontent.com/1050156/73499551-40770d00-4375-11ea-81f3-6887439a0fa5.png)

While the parameter is:
![image](https://user-images.githubusercontent.com/1050156/73499578-4ec52900-4375-11ea-8e94-e201e6b3c03a.png)

Because of the inconsistency in naming, the operation will generate "odatavalue" while the property will actually be called "odata_value"

**Comment by fearthecowboy** [comment]
4.4.167 includes fixes for naming, overrides

**Comment by lmazuel** [comment]
Fixed
