### ISSUE TITLE
Consider supporting x-ms-client-name on headers

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest.modelerfour#151]
We support `x-ms-client-name` almost on everything. Response headers seem like an omission.

**Comment by fearthecowboy** [comment]
I assume that you're talking about header _parameters_? 

I think that there is a bug in the core (either the OAI2 to OAI3 converter, or the tree shaker) that's making extensions follow the schema, instead of propagating to the schema and the parameter.  I looking into see if it's related to #145

**Comment by pakrym** [comment]
Response header definitions like in https://github.com/Azure/autorest.testserver/blob/master/swagger/header.json#L910-L914

**Comment by daviwil** [comment]
This is now implemented in `@autorest/modelerfour@4.15.396`.
