### ISSUE TITLE
Parameter is getting flattened when it should not be when payload-flattening-threshold is set

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest.modelerfour#160]
**Describe the issue**
This caused this error that @kpratico opened: https://github.com/Azure/autorest.python/issues/389

The parameter [file_stream](https://github.com/Azure/azure-rest-api-specs/blob/911f41bbbb59266f01ff8d1ac7fe230cf19a0204/specification/cognitiveservices/data-plane/FormRecognizer/preview/v2.0/FormRecognizer.json#L1370) in [analyze_receipt_async](https://github.com/kristapratico/azure-sdk-for-python/blob/fr-autorestv3/sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/operations/_form_recognizer_client_operations.py#L375) is being incorrectly labeled as having been flattened. We run it with payload-flattening-threshold=2, but it shouldn't be flattened

** REQUIRED ** 
**ModelerFour** version:
4.4.162
**AutoRest-core** version:
3.0.6198
**CommandLine** :
autorest-beta --use=. --add-credentials --payload-flattening-threshold=2 --namespace=azure.ai.formrecognizer --package-name=azure-ai-formrecognizer --no-namespace-folders ---clear-output-folder --output-folder=FormRecognizer/ --input-file=FormRecognizer.json --credential-scopes=https://cognitiveservices.azure.com/.default --basic-setup-py=true --package-version=2.0.0 --output-artifact=code-model-v4-no-tags
OpenAPI/Swagger file: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cognitiveservices/data-plane/FormRecognizer/preview/v2.0/FormRecognizer.json
(***You can't actually generate from this file, i have the version with fixes if you'd like me to send it to you***)

**Comment by fearthecowboy** [comment]
In `4.7.207+  ` this is modeled differently. Has this been resolved?

**Comment by lmazuel** [comment]
Closing in favor of https://github.com/Azure/autorest.modelerfour/issues/163
