### ISSUE TITLE
Handle operation that have binary and schema type of input at the same time

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.modelerfour#162]
Initial suggestion:

> In some scenario, we could want to generate only one SDK operation, from several operations in the Swagger. The `x-ms-logical-operation-extension` would allow to annotate an operation, in order to explain how to group them.
> 
> This intended to fix situation where the input parameters can be anything (bytes or JSON) for instance. This is solved in OAI3, since you can specify different types per content-type, but there is no such thing avialable in Swagger 2 
> 
> This is NOT intended to group operations that have radical different set of parameters or return type (exact validation TBD).
> 

After discussion, that's not necessary in most scenario to have this extension, we could be smarter (see the rest of the thread)

This could be implemented as overload in C#/Java and multiple input type in other language like Python

Useful for FormRecognizer at least.

**Comment by lmazuel** [comment]
Let's hold on on that, after discussion with Johan

**Comment by fearthecowboy** [comment]
From @lmazuel 

- Swagger with multiple serializable content-type, should just generate OAI3 with multiple content with same model. I think it's fair here, and we should not make it complicated (with OAI3 we could say JSON -> Model, XML -> XmlModel, but not here)
- I agree with Darell and Johan that generator should NOT need x-ms-logical-operation, and should be smart enoguh when they see different format to generate smart code. Just need to see what medita-type were in Swager using m4
- What that smart code is, I think it's language dependent:
  - C#/Java can generated one overload per media_type
  - Python can introspect the input type to decide how to serialize it on the fly
- In both language, we will need the virtual parameter you specify at least for binary (JPEG or TIFF?)


I'm ok with that. 
 
If we don't force an operation to be split with x-ms-paths and x-ms-logical-operation, then 
	
- the schema that's specified is always just for object serialization schema/body parameter would be ignored completely for binary payloads.
	 
- we would be implicitly adding the additional request in the operation when there is both kinds (object and binary)
	 
- multiple binary formats in one request would necessitate inferring a header parameter for content-type (or maybe for binary types we always infer a content-type header parameter, and it would be a constant when there is only one possible value)
	 
- Anyone who lazily throws multiple consumes content types may get more than they ask for (which is OK by me, it's their lousy swagger!)
	 
- If there are multiple object serialization media types we 
  - pick the first ?
  - Favor JSON ?
  - Error  ? 
  - add a content-type parameter?

This would require the least change on inputs, (as I can do this all in the core and m4) and you'd get the most flexibility for the user (with the expectation that weird input means weird output)

**Comment by lmazuel** [comment]
Answer
- If I have PDF + text/plain + application/json, I guess it's fair to let generator have their own mapping (we know by design text/* is text, and application/* is binary in general)
- Yes, let's add the optional parameter as you describe
- Yes
- S*** in, S*** out :p 
- I would add a parameter with JSON as default, or first if no JSON

@johanste to shine as well

**Comment by lmazuel** [comment]
Will follow up in https://github.com/Azure/autorest.modelerfour/issues/163
