### ISSUE TITLE
Missing mediaTypes/knownMediaTypes

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.modelerfour#163]
In FormRecognizer:
https://github.com/iscai-msft/azure-rest-api-specs/blob/4cacb377a71fff18cb90276f0158e1e7588fa52e/specification/cognitiveservices/data-plane/FormRecognizer/preview/v2.0/FormRecognizer.json#L217-L223

I would expect to see:
- the full list of mediaTypes of "consumes"
- solved knownMediaType: JSON + bytes

Where I see JSON for now only:
![image](https://user-images.githubusercontent.com/1050156/74073007-9b37e680-49bd-11ea-8a62-9e48a04f7176.png)

**Comment by fearthecowboy** [comment]
After talking with @lmazuel  on this, I think we'll have to infer multiple distinct requests for this operation.

This either means that `Operation` in the code model will have to support multiple possible `Requests`  (ie, `Array<Request>` (which means generating overloads or a suitable experience in a given language) 

All the  `Responses`/`Exceptions`  would all apply to all the `Request`s  - if that's not what's required, the spec would have to split the operation into separate operations using `x-ms-paths` and a `?Binary ` and `?Json` suffixes. 

Conversely, this effect could be synthesized with #162 and grouping two operations into one logical grouping (and would still have to have the same `Response`/`Exceptions` for the logical operation.

**Comment by fearthecowboy** [comment]
Hmm. That still wouldn't clearly solve the different payloads tho' 

We're going to have to do #162 to fix this either way, since assuming binary stream payload based solely on mediatype is IMHO a bit dangerous

**Comment by fearthecowboy** [comment]
`4.7.207`+ has the new media type/multi request modeling

**Comment by lmazuel** [comment]
Didn't try yet, will soon!

**Comment by lmazuel** [comment]
Fixed
