### ISSUE TITLE
Failure to generate azure-mgmt-network

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest.modelerfour#166]
**Describe the issue**
I'm running into errors generating azure-mgmt-network (have only tried 2019-11 and 2019-09). I get the following error:
Error: The 'title' across provided OpenAPI definitions has to match. Found: 'NetworkManagementClient', 'ExpressRouteCrossConnection REST APIs', 'VirtualWANAsAServiceManagementClient', 'WebApplicationFirewallManagement'. Please adjust or provide an override (--title=...).

** REQUIRED ** 
**ModelerFour** version: 4.6.199
**AutoRest-core** version: 3.0.6198
**CommandLine** : autorest-beta test\services\azure-mgmt-network\README.md --use=. --tag=package-2019-11 (running from root of my local autorest.python repo)
OpenAPI/Swagger file: [Here](https://github.com/Azure/autorest.python/blob/add_multiapi_client/test/services/azure-mgmt-network/README.md)'s the readme file i'm using for network:

**Comment by weidongxu-microsoft** [comment]
readme.md has `title` defined. It should get picked.

``` yaml
title: NetworkManagementClient
description: Network Client
openapi-type: arm
```

Or you can add `--title=NetworkManagementClient` to autorest-beta

I think the real problem is that `--tag` is no longer supported in v3.

java works fine with 2019-06-01 (after `tag` is somehow handled).

**Comment by iscai-msft** [comment]
@weidongxu-microsoft tag is now supported in v3, you can try generating with the latest version of autorestv3 (it's readme contains the latest versions of autorest-core and modelerfour as well)
