### ISSUE TITLE
Duplicate global parameters

### ISSUE THREAD

**Issue by annatisch** [Azure/autorest.modelerfour#168]
**Describe the issue**
When generating a Python SDK from the Storage Tables spec, the API version global parameter is duplicated 13 times:
https://github.com/lmazuel/table_proto/blob/antisch-dev/generated/azure_table_storage/_configuration.py#L34

** REQUIRED ** 
**ModelerFour** version: 4.4.162
**AutoRest-core** version: 3.0.6220
**CommandLine** : autorest-beta readme.md --credential-scopes=https://storage.azure.com/.default --tag=package-2019-02 --output-folder="C:\tables\generated" --clear-output-folder --python --use=https://github.com/Azure/autorest.python/releases/download/v5.0.0-dev.20200211.1/autorest-python-5.0.0-dev.20200211.1.tgz --debug --verbose
OpenAPI/Swagger file:
https://github.com/shurd/azure-rest-api-specs/blob/tablesSwagger/specification/cosmos-db/data-plane/readme.md#tag-package-2019-02

**Comment by annatisch** [comment]
FYI @lmazuel

**Comment by fearthecowboy** [comment]
I'm pretty sure that this part is corrected in `4.7.x` -- duplicate constant values have been resolved

**Comment by lmazuel** [comment]
@annatisch could you retry with https://github.com/Azure/autorest.python/releases/download/v5.0.0-dev.20200227.1/autorest-python-5.0.0-dev.20200227.1.tgz ?

**Comment by MiYanni** [comment]
This has not been fixed. Here is the Azure.Storage.Tables swagger we use in CSharp: https://github.com/Azure/autorest.csharp/blob/feature/v3/samples/Azure.Storage.Tables/table.json
The subsequent code model has 10 duplicate Version global parameters being produced: https://github.com/Azure/autorest.csharp/blob/feature/v3/samples/Azure.Storage.Tables/Azure.Storage.Tables/CodeModel.yaml#L1127-L1308
I'm going to mark this as P0 as it is blocking our removal of the manual deduplication process we currently have in place. This was predicated off of this issue: https://github.com/Azure/autorest.modelerfour/issues/100

**ModelerFour** version: 4.9.225
**AutoRest-core** version: 3.0.6237
**AutoRest** version: 3.0.6191

**Comment by fearthecowboy** [comment]
try 4.10.250+ -- it should be fixed for this case too.

**Comment by MiYanni** [comment]
Fixed as of 4.10.250. Closing.
