### ISSUE TITLE
Generates Mgmt Storage: missing ApiVersion parameter

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.modelerfour#170]
Generating:
https://github.com/Azure/autorest.python/blob/add_multiapi_client/test/services/azure-mgmt-storage/README.md

All operations are missing api-version as query parameters

**Comment by fearthecowboy** [comment]
Refactoring API version handling entirely -- see # 173

**Comment by lmazuel** [comment]
Working now, don't ask me why....
