### ISSUE TITLE
Profile/API Version Rollup. [Proposal] [Replaces #81 , #90, #91, #93, #94, #170]

### ISSUE THREAD

**Issue by fearthecowboy** [Azure/autorest.modelerfour#173]
In order to solve the how to represent API versions, we're adding configuration
to define how to interpret them.

Replacing Issues  #81 , #90, #91, #93, #94, #170 

## New Configuration settings
`--api-version-mode` :`auto` | `client` | `method`| `profile` | `none`
`--api-version-parameter`: `choice` | `constant`
`--use-model-namespace`: `true` | `false`

### Existing related configuration
`--profile:[...]` - selects the profiles supported for generation. 
  Filters operations to the possible versions provided by profiles: { ... } configuration
  
`--api-version:[...]` filters API versions to a given set of possible API versions. 
   does not infer how to treat API version, just filters APIs to those provides. 

### `--api-version-mode` 
- `auto` (or unspecified) - guesses which mode it should use:
  - if `--profile:[...]` is specified, it uses `profile`
    
  - if all operations have a single API version, uses `client` 
    (it's OK if some APIs don't have an `api-version` parameter). 
    Defaults:
      `--api-version-parameter:constant`
      `--use-model-namespace:false`
  
  - if operations have a single API version each, but API has multiple API versions 
    uses `method`
    Defaults:
      `--api-version-parameter:constant`
      `--use-model-namespace:false`
    
  - if there are individual operations that have more than one API version, 
    it will use 'method'
    Defaults:
      `--api-version-parameter:choice`
      `--use-model-namespace:true`
  
  - if no operations have a detected `api-version` parameter, uses `none`
    Defaults:
      `--api-version-parameter:undefined` // not important
      `--use-model-namespace:false`

- `client` - generates a single parameter in the client for API version (choice/constant)
      
- `method` - generates a parameter in each applicable operation (choice/constant)
    
- `profile` - generates a profile client parameter
  - each method is tagged with which profiles are supported for a given method
    and gets a virtual parameter of type `conditional` that selects the API 
    version based on the selected global profile parameter. 
  
  - if profile:auto (or no profiles are defined), it will attempt to create 
    profiles based on the operations found. 
  
### `--api-version-parameter`
 - `choice` - generates a parameter, and an enum (not sealed) 
    to represent the api versions. User may manually set the api-version 
 
  - `constant` - generates constant parameters to force the API version to a 
    given value. Not user mutable. 
  
### `--use-model-namespace` : 

- true - sets the namespace for each model to a value based on the API verison 
  that the model is first found.

- false - all models are in a single unnamed namespace

**Comment by lmazuel** [comment]
@fearthecowboy this means we ignore the position of api_version in the Swagger (method/client). I guess it's fair in most Swagger.
What are the criteria to assess a given parameter is the api version? called ApiVersionParameter? Rest name being a query `api-version`?

**Comment by fearthecowboy** [comment]
if it's called `api-version` or `api-version` and it's a query parameter. we can refine the definition if you'd like, and/or make it configurable.

**Comment by fearthecowboy** [comment]
I've published `4.9.225 ` -- it's very new, give it a shot-- it has the first round of this in there (no profiles). (it rolls up a lot of small changes, so hopefully no big bumps)
