### ISSUE TITLE
Description override

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.modelerfour#179]
This Swagger:
```
    "MetricSpecification": {
      "description": "Metric specification of operation.",
      "properties": {
        "dimensionX": {
          "$ref": "#/definitions/Dimension",
          "description": "The dimension X"
        },
        "dimensionY": {
          "$ref": "#/definitions/Dimension",
          "description": "The dimension Y"
        }
      }
    },
    "Dimension": {
      "description": "Dimension of blobs, possibly be blob type or access tier.",
      "properties": {
        "name": {
          "type": "string",
          "description": "Display name of dimension."
        },
```

Should generate property descrition "The dimension X" "The dimension Y", and type class docstring "Dimension of blobs, possibly be blob type or access tier."

We tested and m4 as of today put "Dimension of blobs, possibly be blob type or access tier." everywhere.

This was ok with autorestv2, and don't think that hurts to support and make huge better doc.

I don't put P0 because it's not technically blocking, but important P1 to me (let's say P0.5 :p)

**Comment by fearthecowboy** [comment]
ah, yes, the description beside $ref.

It'll be in my next push.

**Comment by lmazuel** [comment]
Fixed
