### ISSUE TITLE
Property with reference type becomes an And schema

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.modelerfour#18]
So, looking at Dns, RecordSet has a property called `properties`. 
https://github.com/Azure/azure-rest-api-specs/blob/f8a99d2a884f76df769e3bd4d5d5d189a051d8f7/specification/dns/resource-manager/Microsoft.Network/stable/2018-05-01/dns.json#L1422-L1451
The `"$ref"` for the `properties` property is for `RecordSetProperties`. `RecordSetProperties` is just a bunch of properties (nothing too odd with it).

However, when this gets created in the code model as this:
![image](https://user-images.githubusercontent.com/17788297/66879419-d3c93580-ef72-11e9-9a97-e455555d0570.png)

So, it creates an `And` schema for this. But, why? The property is just a `"$ref"` to `RecordSetProperties`. Unless multiple `"$ref"` is allowed, this should never get created as an `And` schema. My assumption is that `"$ref"` is similar to `"type"` where `"type"` is a conceptual type (string, array, object, integer, etc.) where `"$ref"` is a real type (one that is actually defined in the swagger itself). So, representing it as an `And` is inaccurate if you're simply binding a type reference to that property. Am I wrong? 🤐

**Comment by fearthecowboy** [comment]
Yeah, this doesn't look correct. it should create an and schema only if it has additionalProperties or a parent schema.

**Comment by fearthecowboy** [comment]
Refactored, removed AndSchemas. Assuming this isn't an issue anymore
