### ISSUE TITLE
Prevent parameter flattening for multiple requests input

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.modelerfour#181]
Assuming I have a method that could take both a JSON with a signature `Foo(name, address)` and a binary. Assuming flattening, in overload language C#/Java, I could generate:

```
public void analyze(string name, string address); // Flattening overload of JSON

public void analyze(bytes input); // The binary
```

In Python, I'm blocked, since I need one signature only, so I would want something like:
```python
def analyze(self, input: typing.Any)
```

which would mean disable parameter flattening when the operation has multiple requests.

I was thinking (hoping? :)) a parameter in my Python readme to say to m4 `multiple-request-parameter-flattening: false`, and let true by default for overload language as default.

**Comment by lmazuel** [comment]
Note that we thought about parameter grouping and model flattening, both would work fine.

**Comment by fearthecowboy** [comment]
Adding in support for `multiple-request-parameter-flattening` -- we may need to tweak this once we see how multiple api versions affect things.

**Comment by fearthecowboy** [comment]
I've published `4.9.225 ` -- it's very new, give it a shot. (it rolls up a lot of small changes, so hopefully no big bumps)

**Comment by lmazuel** [comment]
Trying it right now https://github.com/Azure/autorest.python/pull/582

**Comment by lmazuel** [comment]
We were able to get it to work fine :)

**Comment by daviwil** [comment]
Awesome, thanks for verifying!
