### ISSUE TITLE
Parameter not being correctly flattened out when generating azure-mgmt-advisor

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest.modelerfour#182]
**Describe the issue**
With a payload flattening threshold of 2, [SuppressionContract](https://github.com/Azure/azure-rest-api-specs/blob/2df17398750388e7a8e51eeedaac8bfe099e612b/specification/advisor/resource-manager/Microsoft.Advisor/stable/2017-04-19/advisor.json#L1024) is not being flattened out

** REQUIRED ** 
**ModelerFour** version: 4.7.207
**AutoRest-core** version: 3.0.6233
**CommandLine** :
OpenAPI/Swagger file: autorest-beta ..\azure-rest-api-specs\specification\advisor\resource-manager\readme.md --use=. --python-sdks-folder=F:\azure-sdk-for-python\sdk --python --python-mode=update --keep-version-file --tag=package-2017-04

**Comment by fearthecowboy** [comment]
Need to use the fix in the [python repo](https://github.com/Azure/autorest.python/pull/442)
