### ISSUE TITLE
ApiVersion parameter missing in operation related to GenericResource

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest.modelerfour#183]
**Describe the issue**

For GenericResource, `api-version` is need as input by user. Since it is generic resource (it could be any resource maintained by other services, e.g. compute, web, sql, etc.), the `api-version` in resource.json will not work. Correct `api-version` has to be the specific api-version used by the specific provider.

Therefore we need a way for modelerfour to distinguish this special case. Any form is acceptable, we just need a way to tell it part from other common operations.

GenericResource JSON on `api-version` (it is defined inline):
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Resources/stable/2019-08-01/resources.json#L3056-L3062

Other common JSON on `api-version`:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Resources/stable/2019-08-01/resources.json#L2492-L2494

** REQUIRED ** 
**ModelerFour** version: 4.6.200 and 4.8.221
**AutoRest-core** version: 3.0.6237
**CommandLine** :
OpenAPI/Swagger file: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Resources/stable/2019-08-01/resources.json

**Comment by weidongxu-microsoft** [comment]
Quote from Hamid Tirmizi <hamidt@microsoft.com>

> Let’s rephrase that: Each RP owns a number of types of resources. A small number of them are owned by ARM, since sometimes ARM can be seen as an RP too.
> 
> When you are creating a resource of a particular type, the API version guidance comes from the RP.
> 
> When you are creating a resource of type owned by ARM (e.g. deployment, tag etc.), the API version from the ARM client can be used, since ARM knows the API version needed.
> 
> When you are creating a resource of type owned by another RP (e.g. virtualMachines by Compute RP), the API version comes from the Compute RP.
> 
> Now as customer you have two options to access the resource:
> 1.	ARM allows you to access any resource in a generic manner, so use ARM client if you know the API version to use. (Yes, one way of knowing the API version would be to fail and look at the error message)
> 2.	Use the RPs own client, e.g. Compute RP client, which is likely to have the correct API version built in.
>

**Comment by fearthecowboy** [comment]
Yeah, we're going to have to put in an configuration for how that api-version parameter gets handled.

**Comment by fearthecowboy** [comment]
with `4.10.250`+ you can add an extension to a parameter `"x-ms-api-version": false ` to tell it not to treat it like an api version, just a regular parameter.

Add that to the parameter and m4 won't try to do any special handling.

**Comment by weidongxu-microsoft** [comment]
Works good.

Let me see if I can get this to spec.
