### ISSUE TITLE
content type parameter being generated doesn't have an 'implementation' in its yaml

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest.modelerfour#185]
**Describe the issue**
content type parameter generated for [this](https://github.com/Azure/azure-rest-api-specs/blob/1ed17c5bfe14a277d513bf0443680bcf84ee2a39/specification/storage/data-plane/Microsoft.BlobStorage/preview/2019-07-07/blob.json#L6576) operation doesn't have an 'implementation' entry in its yaml

** REQUIRED ** 
**ModelerFour** version: 4.7.207
**AutoRest-core** version: 3.0.6233
**CommandLine** :  autorest ..\azure-sdk-for-python\sdk\storage\azure-storage-blob\swagger\README.md --use=. --python-sdks-folder=..\azure-sdk-for-python\sdk --python
OpenAPI/Swagger file: https://github.com/Azure/azure-rest-api-specs/blob/storage-dataplane-preview/specification/storage/data-plane/Microsoft.BlobStorage/preview/2019-07-07/blob.json

**Comment by fearthecowboy** [comment]
Duplicate to #177. Already fixed in 4.7.211
