### ISSUE TITLE
Content type parameter being added for storage even though there's only one request

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest.modelerfour#187]
**Describe the issue**
A content type parameter is being added for azure-storage-blob for [this](https://github.com/Azure/azure-rest-api-specs/blob/1ed17c5bfe14a277d513bf0443680bcf84ee2a39/specification/storage/data-plane/Microsoft.BlobStorage/preview/2019-07-07/blob.json#L6576) operation even though there's only one request that gets generated.
** REQUIRED ** 
**ModelerFour** version: 4.7.207
**AutoRest-core** version: 3.0.6233
**CommandLine** : autorest ..\azure-sdk-for-python\sdk\storage\azure-storage-blob\swagger\README.md --use=. --python-sdks-folder=..\azure-sdk-for-python\sdk --python
OpenAPI/Swagger file: https://github.com/Azure/azure-rest-api-specs/blob/storage-dataplane-preview/specification/storage/data-plane/Microsoft.BlobStorage/preview/2019-07-07/blob.json

**Comment by fearthecowboy** [comment]
Is it a constant parameter?

**Comment by fearthecowboy** [comment]
Oh, it might be creating one even if there is only one possibility.

I can change that so it's only doing that if there is more than one media type.

**Comment by iscai-msft** [comment]
perfect, thanks so much!

**Comment by fearthecowboy** [comment]
I've published `4.9.225` -- it's very new, give it a shot. (it rolls up a lot of small changes, so hopefully no big bumps)
