### ISSUE TITLE
Incorrect YAML Tags for types

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.modelerfour#188]
**Describe the issue**
## Issue 1
Swagger: https://github.com/Azure/autorest.csharp/blob/feature/v3/test/TestProjects/TypeSchemaMapping/TypeSchemaMapping.json
![image](https://user-images.githubusercontent.com/17788297/75484132-080b2480-595d-11ea-8906-2023309b9a91.png)
Instead of `HttpWithBodyRequest` that should be `HttpBinaryRequest`.

## Issue 2
Swaggers:
- https://github.com/Azure/autorest.testserver/blob/master/swagger/url.json
- https://github.com/Azure/autorest.testserver/blob/master/swagger/body-boolean.json
![image](https://user-images.githubusercontent.com/17788297/75487950-3f310400-5964-11ea-84d3-fcc772617638.png)

The type tag is missing when it should be `HttpRequest`.

** REQUIRED ** 
**ModelerFour** version: 4.8.221
**AutoRest-core** version: 3.0.6237
**AutoRest** version: 3.0.6191

**Comment by fearthecowboy** [comment]
I've published `4.9.225 ` -- it's very new, give it a shot. (it rolls up a lot of small changes, so hopefully no big bumps)

**Comment by MiYanni** [comment]
Both issues have been fixed! Closing.
