### ISSUE TITLE
The choiceType schema in ChoiceSchema does not propegate to the Schemas collections

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.modelerfour#19]
So, this:
![image](https://user-images.githubusercontent.com/17788297/66972213-c1b9c680-f048-11e9-85c4-eaabcb92db86.png)

You can see it is not referenced. Since it has no reference, it means that the StringSchema defined here does not end up in the `strings` collection in the `Schemas` node.

**Comment by fearthecowboy** [comment]
Fixed in https://github.com/Azure/autorest.modelerfour/commit/82841feb35f26d614e9d5cbf2cd71d8f3b165ddb

**Comment by MiYanni** [comment]
Fixed.
