### ISSUE TITLE
Duplicate parameter name during parameter flattening

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest.modelerfour#191]
**Describe the issue**
Geting duplicate parameter name "name" when KeyInfo gets flattened for [create_or_update_function_secret](https://github.com/Azure/azure-rest-api-specs/blob/4389594677a51062d017ee9381bf6d2ff89eaa76/specification/web/resource-manager/Microsoft.Web/stable/2019-08-01/WebApps.json#L3360)

** REQUIRED ** 
**ModelerFour** version: 4.7.207
**AutoRest-core** version: 3.0.6233
**CommandLine** :  autorest ..\azure-rest-api-specs\specification\web\resource-manager\readme.md --use=. --multiapi --python-sdks-folder=..\azure-sdk-for-python\sdk --python
OpenAPI/Swagger file:https://github.com/Azure/azure-rest-api-specs/blob/master/specification/web/resource-manager/Microsoft.Web/stable/2019-08-01/WebApps.json

**Comment by fearthecowboy** [comment]
#192 should solve it; conflict resolution in parameter names with formatting.

**Comment by fearthecowboy** [comment]
try with `v4.9.232 `  -- I get 
![image](https://user-images.githubusercontent.com/133736/75574294-f7b58100-5a12-11ea-8303-a8d46c628a84.png) now
