### ISSUE TITLE
SchemaContext and KnownMediaType are not ref'ed in code model's schema

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.modelerfour#196]
**Describe the issue**
Basically, these types are not reused in the code model's schema. Therefore, they don't appear as refs, which means they are considered as 'separate types'. This is problematic for C# or other typed languages.
![image](https://user-images.githubusercontent.com/17788297/75725776-10819900-5c96-11ea-8683-459a3193d40d.png)

You can see in the all-in-one schema how `serializationFormats` has no ref to `KnownMediaType`
https://github.com/Azure/perks/blob/master/codemodel/.resources/all-in-one/yaml/code-model.yaml#L666
The same thing occurs for `usage` not using `SchemaContext`.

** REQUIRED ** 
**ModelerFour** version: 4.9.225
**AutoRest-core** version: 3.0.6237
**AutoRest** version: 3.0.6191

**Comment by daviwil** [comment]
Try `@autorest/modelerfour@4.10.242` and let me know if this is fixed for you!

**Comment by MiYanni** [comment]
Fixed. Thank you! Closing.
