### ISSUE TITLE
Binary media type not using HttpBinaryRequest type tag

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.modelerfour#197]
**Describe the issue**
Basically, when a request is an actual binary request, it is incorrectly using the `HttpWithBodyRequest` tag instead of the `HttpBinaryRequest` tag. This causes deserialization issues for C#.
![image](https://user-images.githubusercontent.com/17788297/75726129-a4536500-5c96-11ea-8287-990d8458c4d4.png)
This is from the `media_types.json` swagger on the test server.

** REQUIRED ** 
**ModelerFour** version: 4.9.225
**AutoRest-core** version: 3.0.6237
**AutoRest** version: 3.0.6191

**Comment by pakrym** [comment]
Hitting this in form analytics.

**Comment by daviwil** [comment]
Try `@autorest/modelerfour@4.10.242` and let me know if this is fixed for you!

**Comment by MiYanni** [comment]
Fixed. Thank you! Closing.
