### ISSUE TITLE
Add uid to Schema nodes

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.modelerfour#20]
Have a uid for all schemas `schema:X`, similar to the uid for properties `property:X` and parameters `parameter:X`.

**Comment by fearthecowboy** [comment]
I've been thinking about this; I think there is a better way to solve it on your side. 

Just add an `internal int uid`property that gets set on object creation in your generated classes.

**Comment by MiYanni** [comment]
I ended up doing something similar. For every schema, I added my own Uid to the CSharpLanguage node. However, in doing so, surfaced this issue: https://github.com/Azure/autorest.modelerfour/issues/19
So, I end up missing nodes to add this Uid to, since those schemas are missing from the Schemas node.
