### ISSUE TITLE
Content-Type as header parameter

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.modelerfour#207]
**Describe the issue**
When you have multiple media types, you end up with a parameter that looks like this:
![image](https://user-images.githubusercontent.com/17788297/76256033-7d53e080-620c-11ea-8c53-bb28c78c1fb0.png)

However, it doesn't really describe itself well. It is missing protocol information, and the serialized name (`Content-Type`). Since we have support for header parameters, why not make `Content-Type` always a header parameter? When it is only a single value, it would be a constant header parameter, and when it is multiple values, it is the same sealed choice that it creates right now. Sometimes, this seems to happen. For example, in the header.json from the test server:
![image](https://user-images.githubusercontent.com/17788297/76256757-b5a7ee80-620d-11ea-9ba6-4253bd17f851.png)

However, I believe this should happen for every request. It would make handling the Content-Type header extremely consistent.

** REQUIRED ** 
**ModelerFour** version: 4.9.225
**AutoRest-core** version: 3.0.6237
**AutoRest** version: 3.0.6191
Swagger: https://github.com/Azure/autorest.testserver/blob/master/swagger/media_types.json

**Comment by fearthecowboy** [comment]
I'm adding a configuration to enable this:

``` yaml
modelerfour:
  always-create-content-type-parameter: true 
```

**Comment by fearthecowboy** [comment]
will be in #223

**Comment by fearthecowboy** [comment]
Try `4.10.252`

**Comment by pakrym** [comment]
I don't see any change in codemodel:

```
use-extension:
  "@autorest/modelerfour": "4.10.254"
modelerfour:
  always-create-content-type-parameter: true
```

**Comment by fearthecowboy** [comment]
It just occured to me that you probably want this on non-binary-payload operations too.

**Comment by pakrym** [comment]
Right, the goal is not to have any special logic for the content-type parameter and treat is as a normal header parameter.

**Comment by fearthecowboy** [comment]
Putting this in serialized-body-payload operations will cause a slight change -- if the `consumes` says `["application/json","text/json"]`  you're going to get a parameter that has an enum where it could be either of the values -- previously the assumption was 'pass the first one'. 

I'm not sure you want that. 

I can either make that assumption up front (ie, pick the first one, and keep it a constant) or ... we can yell at the developer to fix the swagger if they don't like that behavior.

I'm leaning towards just picking the first one.

**Comment by pakrym** [comment]
> previously the assumption was 'pass the first one'.

If every generator has to make the same assumption I think it's better to make it in M4, in that case if some logic needs to change generators won't have to react and would still be consistent.

> I'm leaning towards just picking the first one.

👍

**Comment by fearthecowboy** [comment]
Try `4.10.258`

**Comment by pakrym** [comment]
Nope,

Generated parameter doesn't have a protocol correctly set:

```
  - !<!Parameter> 
        schema: *ref_105
        implementation: Method
        language: !<!Languages> 
          default:
            name: contentType
            description: Body Parameter content-type
        protocol: !<!Protocols> {}
```

Should be 
```
        protocol: !<!Protocols> 
          http: !<!HttpParameter> 
             in: header

```

**Comment by fearthecowboy** [comment]
ah, hell.  Added. try 4.10.260

(how did this not come up for python? Even for the binary parameters, this should have triggered something)

**Comment by pakrym** [comment]
Still no, http doesn't have a type specifier:

```
    protocol: !<!Protocols> 
          http:
            in: header
```

**Comment by fearthecowboy** [comment]
Sorry; having a hard time concentrating this mornig. I think I'm feeling worse and worse as the day goes.

4.10.263

**Comment by pakrym** [comment]
One other thing, the parameter has to have `serializedName: Content-Type` or it will end up having a wrong name.

**Comment by fearthecowboy** [comment]
4.10.266. 

Please let this be it. I'm gonna go lie down now.

**Comment by pakrym** [comment]
`serializedName` is wrong, it has to be `Content-Type` not `'contentType'`

**Comment by fearthecowboy** [comment]
4.10.268
