### ISSUE TITLE
Parameters not getting flattened in operation

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest.modelerfour#208]
**Describe the issue**
When generating attestation, creationparams under (create)[https://github.com/Azure/azure-rest-api-specs/blob/f0e5030929b9bbeacc13249c309b5b14cbbdedef/specification/attestation/resource-manager/Microsoft.Attestation/preview/2018-09-01-preview/attestation.json#L112] is not getting flattened.

It's mentioned both in the readme and in my command line, since this was an issue a while ago

Comparison between old autorest and autorest v3 generated code:
![image](https://user-images.githubusercontent.com/43154838/76357006-443f6d00-62ed-11ea-80f4-a1a1a057df01.png)

** REQUIRED ** 
**ModelerFour** version: 4.9.234
**AutoRest-core** version: 3.0.6246
**CommandLine** : autorest ../azure-rest-api-specs/specification/attestation/resource-manager/readme.md --use=. --python-sdks-folder=../azure-sdk-for-python/sdk --python --python-mode=update --keep-version-file --multiapi --payload-flattening-threshold=2
OpenAPI/Swagger file: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/attestation/resource-manager/Microsoft.Attestation/preview/2018-09-01-preview/attestation.json

**Comment by fearthecowboy** [comment]
I'm curious why this should be flattened?

`AttestationServiceCreationParams` has three properties: `location`, `tags`, `properties`

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/attestation/resource-manager/Microsoft.Attestation/preview/2018-09-01-preview/attestation.json#L492

and `AttestationServiceCreationSpecificParams` doesn't have `x-ms-client-flatten` so it doesn't get it's properties flattened up to the parent?
