### ISSUE TITLE
Default name for properties has the parent type in it, instead of just the property name (serializedName)

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.modelerfour#21]
![image](https://user-images.githubusercontent.com/17788297/66972431-6fc57080-f049-11e9-8952-c2052c8c0820.png)

**Comment by fearthecowboy** [comment]
Ah, yeah, I see what happened here. Easy fix.

**Comment by fearthecowboy** [comment]
Updated `@autorest/modelerfour` to  `4.0.24 ` ... do an `autorest-beta --reset` to update.

**Comment by MiYanni** [comment]
Fixed.
