### ISSUE TITLE
Add schema usage info

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.modelerfour#23]
This would add information about if the schema is used as:
- Input (operation parameter)
- Output (operation response)
- Neither (unreferenced schema)
- Both (Input and Output)

This involves walking the schema hierarchy for a given schema, because, for example, input schemas can contain properties, and those property schemas would also need to be marked as input.

**Comment by fearthecowboy** [comment]
+ Add the possible formats that the model can be serialized from to (XML, JSON, FORM) so that the generator can opt not to generate code for something that's never programmatically possible.

**Comment by daviwil** [comment]
Forgot to close this one out!  The new fields on `ObjectSchema` that track schema usage are `usage` which is an array of values `input` and `output` for when the schema is used as a parameter or response in an operation.  I also walk the schema inheritance graph to make sure all parents and children of a given schema reflect this information.

We also track the media types the schema is used with in `serializationFormats` which is an array of `KnownMediaType` values (`json`, `xml`, etc).

Hope it helps!

**Comment by daviwil** [comment]
Whoops, reopening until this is confirmed.

**Comment by MiYanni** [comment]
This generally has been implemented. I'll make separate issues for any other problems that occur related to it. Closing.
