### ISSUE TITLE
Readonly attribute not showing up in m4 output

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest.modelerfour#232]
**Describe the issue**
readonly is not showing up as true even though it's set in the swagger: https://github.com/Azure/azure-rest-api-specs/blob/b4b98c3f08e52adf68f21ea2c01b1e74f3a370ea/specification/keyvault/resource-manager/Microsoft.KeyVault/stable/2019-09-01/keyvault.json#L1665

I'm also confused because it appears the readonly attribute is defined on the schema in the specification, but when I look at various code model outputs, the readonly attribute is defined on the property, not the schema itself.

<img width="691" alt="Screen Shot 2020-03-25 at 12 51 15 PM" src="https://user-images.githubusercontent.com/43154838/77563219-5b5a8f00-6e97-11ea-890e-652893033670.png">

<img width="544" alt="Screen Shot 2020-03-25 at 12 32 03 PM" src="https://user-images.githubusercontent.com/43154838/77561490-28170080-6e95-11ea-8a74-071be7650739.png">

** REQUIRED ** 
**ModelerFour** version: 4.10.252
**AutoRest-core** version: 3.0.6258
**CommandLine** : autorest ../azure-rest-api-specs/specification/keyvault/resource-manager/readme.md --python --python-sdks-folder=../azure-sdk-for-python/sdk --output-artifact=code-model-v4-no-tags --use=.
OpenAPI/Swagger file: https://github.com/Azure/azure-rest-api-specs/blob/b4b98c3f08e52adf68f21ea2c01b1e74f3a370ea/specification/keyvault/resource-manager/Microsoft.KeyVault/stable/2019-09-01/keyvault.json

**Comment by fearthecowboy** [comment]
@iscai-msft  -- this got fixed a while back, right? Can you confirm?

**Comment by iscai-msft** [comment]
@fearthecowboy: yes, apologies, I will go through the fixed please confirm now as well
