### ISSUE TITLE
Add "time" format to string type

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.modelerfour#233]
The same way we have "format=date-time", add a "time" format
https://en.wikipedia.org/wiki/ISO_8601#Times

Would need that for FormRecoignizer

**Comment by fearthecowboy** [comment]
Please test with #238 and give a thumbs up if your satisfied with the results.

**Comment by iscai-msft** [comment]
@fearthecowboy this is working, tested the pr. thanks for your help!
