### ISSUE TITLE
Unable to generate AnomalyDetector

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.modelerfour#242]
:\Users\lmazuel\AppData\Roaming\npm\autorest.CMD C:\Users\lmazuel\Git\azure-rest-api-specs\specification\cognitiveservices\data-plane\AnomalyDetector\readme.md --keep-version-file --multiapi --no-async --python --python-mode=update --python-sdks-folder=C:\Users\lmazuel\Git\azure-sdk-for-python\TEST --use=@autorest/python@5.0.0-dev.20200326.1
AutoRest code generation utility [cli version: 3.0.6187; node: v10.15.3, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\lmazuel\.autorest\@autorest_core@3.0.6262\node_modules\@autorest\core\dist' (3.0.6262)
   Loading AutoRest extension '@autorest/python' (5.0.0-dev.20200326.1->5.0.0-dev.20200326.1)
   Loading AutoRest extension '@autorest/modelerfour' (4.12.276->4.12.276)
FATAL: Error: Enum types of 'undefined' and format 'undefined' are not supported. Correct your input (AnomalyDetectorErrorCodes).
  Error: Plugin modelerfour reported failure.

**Comment by fearthecowboy** [comment]
This should be fixed with #251 -- can you try that build and confirm?

**Comment by lmazuel** [comment]
@fearthecowboy 

> WARNING (Modeler/MissingType): The enum schema 'AnomalyDetectorErrorCodes' with an undefined type and enum values is ambigious. This has been auto-corrected to 'type:string'

So I think fixed

**Comment by fearthecowboy** [comment]
published in `4.12.301`

**Comment by lmazuel** [comment]
Confirmed, thanks!
