### ISSUE TITLE
Expose securityDefinitions in some capacity

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/autorest.modelerfour#244]
**Describe the issue**
Swaggers define a `securityDefinitions` section as an indication that the operations require authentication.  Omission of this section indicates no authentication is required.  Today the modeler doesn't expose this at all so there's no way to make the distinction.

For languages like Go that don't support function overloading, it would be preferable to emit a credential parameter in client constructors only if specified as required by the swagger.

I personally don't care about the contents of `securityDefinitions`, just whether it's been defined or not.  So feel free to expose as little (or all) of it as is convenient.

** REQUIRED ** 
**ModelerFour** version: 4.8.221
**AutoRest-core** version: 3.0.6262
**CommandLine** :

autorest --use=\git\Azure\autorest.go --license-header=MICROSOFT_MIT_NO_VERSION --input-file=https://raw.githubusercontent.com/Azure/azure-rest-api-specs/storage-dataplane-preview/specification/storage/data-plane/Microsoft.BlobStorage/preview/2019-07-07/blob.json --namespace=azblob --output-folder=\git\Azure\autorest.go\test\storage\2019-07-07\azblob

**Comment by fearthecowboy** [comment]
working on this now.

**Comment by fearthecowboy** [comment]
in 4.13.xx+

**Comment by jhendrixMSFT** [comment]
This is working for me, thanks!
