### ISSUE TITLE
Unable to generate datamigration

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.modelerfour#247]
Not sure yet if Swagger issue

C:\Users\lmazuel\AppData\Roaming\npm\autorest.CMD C:\Users\lmazuel\Git\azure-rest-api-specs\specification\datamigration\resource-manager\readme.md --keep-version-file --multiapi --no-async --python --python-mode=update --python-sdks-folder=C:\Users\lmazuel\Git\azure-sdk-for-python\TEST --use=@autorest/python@5.0.0-dev.20200326.1
AutoRest code generation utility [cli version: 3.0.6187; node: v10.15.3, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\lmazuel\.autorest\@autorest_core@3.0.6262\node_modules\@autorest\core\dist' (3.0.6262)
   Loading AutoRest extension '@autorest/python' (5.0.0-dev.20200326.1->5.0.0-dev.20200326.1)
   Loading AutoRest extension '@autorest/modelerfour' (4.12.276->4.12.276)
  Error: Assignment: Value '$ref' may not be undefined.

**Comment by fearthecowboy** [comment]
Duplicate: confirmed -- the same underlying issue as #248 (with the exception that it doesn't have a sloppy enum)

**Comment by fearthecowboy** [comment]
I am however going to force the sanity checker at the end to halt on errors (which it hasn't been doing)

**Comment by fearthecowboy** [comment]
See #248 for test instructions (and #251)

**Comment by lmazuel** [comment]
Now I get 
> ERROR (): Two object schemas have name 'AvailableServiceSku' in the same namespace ''-- you must add a client name.
so I guess the problem itself is solved :)
