### ISSUE TITLE
Unable to generate Reservations

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.modelerfour#248]
Not sure yet if Swagger or M4

C:\Users\lmazuel\AppData\Roaming\npm\autorest.CMD C:\Users\lmazuel\Git\azure-rest-api-specs\specification\reservations\resource-manager\readme.md --keep-version-file --multiapi --no-async --python --python-mode=update --python-sdks-folder=C:\Users\lmazuel\Git\azure-sdk-for-python\TEST --use=@autorest/python@5.0.0-dev.20200326.1
AutoRest code generation utility [cli version: 3.0.6187; node: v10.15.3, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\lmazuel\.autorest\@autorest_core@3.0.6262\node_modules\@autorest\core\dist' (3.0.6262)
   Loading AutoRest extension '@autorest/python' (5.0.0-dev.20200326.1->5.0.0-dev.20200326.1)
   Loading AutoRest extension '@autorest/modelerfour' (4.12.276->4.12.276)
  Error: Assignment: Value '$ref' may not be undefined.

**Comment by fearthecowboy** [comment]
That spec has a enum schema (`ResourceTypeNames`) that doesn't have a `type`  -- which lousy input, but that's not the ultimate problem here.

There are two defects here:
 - an issue in the core with merging the specs  
 - after fixing the above, the enum without a type throws an error in m4. Adding in code to allow it to assume string if all the values are strings.

**Comment by fearthecowboy** [comment]
Fix available to test:
- use autorest `--version:3.0.6265` 
- (#251 ) fixes the enum without type info problem ( see [instructions ](https://github.com/Azure/autorest.modelerfour/pull/251#issuecomment-606789930) to test)

**Comment by lmazuel** [comment]
@fearthecowboy fixed with the PR

**Comment by fearthecowboy** [comment]
Published in `v4.12.301`

**Comment by lmazuel** [comment]
Confirmed, thanks!
