### ISSUE TITLE
x-ms-client-default not working

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.modelerfour#268]
It should be adding a `clientDefaultValue` property to the code model YAML. Currently, it does not seem to do that. The logic for default values in global parameter is working (adds `clientDefaultValue`) but this mechanism using `x-ms-client-default` for regular parameters doesn't seem to do anything. The data for this extension also doesn't appear in `extensions`, so it must be getting eaten somewhere.

I was changing the test server swagger to look like this:
![image](https://user-images.githubusercontent.com/17788297/79608471-ec451480-80a9-11ea-8362-694aeb68badc.png)

So, the swagger doesn't have these changes. But, I was testing out `x-ms-client-default` using it.

** REQUIRED ** 
**ModelerFour** version: 4.13.312
**AutoRest-core** version: 3.0.6277
OpenAPI/Swagger file: https://github.com/Azure/autorest.testserver/blob/master/swagger/azure-special-properties.json

**Comment by daviwil** [comment]
Now that I look at this, it seems like we don't propagate `x-ms-client-default` to the OpenAPI 3 document.  All of the code is in place in `modelerfour` to support it though.  Might be an easy fix, we'll see.

**Comment by daviwil** [comment]
@lmazuel confirmed that this is working correctly for the Python generator with the latest m4 release (4.15.378).
