### ISSUE TITLE
x-nullable not working

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.modelerfour#269]
According to here: https://github.com/Azure/autorest/blob/master/docs/extensions/readme.md#x-nullable
It should be able to be specified on a request body, response body, schema usage (ref or in-line declaration), and properties/parameters. Right now, it seems like it is either A, not handled (comes out in the extensions list) or B, handling is broken (not in extensions list, but nothing else changes either). I only tested it on a property, a parameter, and a response, but none of them worked properly. There is a `Nullable` property for Value in the code model that should be holding this information. There are not test server tests for this (yet). 

** REQUIRED ** 
**ModelerFour** version: 4.13.312
**AutoRest-core** version: 3.0.6277
OpenAPI/Swagger file: Modified an existing one and compared code model output

**Comment by daviwil** [comment]
This is now implemented in `@autorest/modelerfour@4.14.364`.  Please give it a shot and let me know if it helps!  /cc @pakrym

**Comment by pakrym** [comment]
Works in most cases, if there are new bugs I'll file them separately.
