### ISSUE TITLE
Generating constant properties

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest.modelerfour#27]
In the case where there's an enum with only one value, autorest should not expose it to customers, just make it a constant. See RefColorConstant in BodyString test.

**Comment by fearthecowboy** [comment]
This got fixed yesterday -- constants now show up as constants https://github.com/Azure/autorest.modelerfour/blob/master/modelerfour/test/outputs/body-string/code-model-v4.yaml#L68

**Comment by iscai-msft** [comment]
fixed!
