### ISSUE TITLE
"Recursing!" error occurs when using modelerfour for the MSGraph swagger

### ISSUE THREAD

**Issue by RodgeFu** [Azure/autorest.modelerfour#282]
**Describe the issue**
we hit following error when trying the new codegen for MSGraph, modelerfour throw error "Recursing" without more details. 

** REQUIRED ** 
**ModelerFour** version: 4.13.348
**AutoRest-core** version: Latest
**CommandLine** :  the command is based on my local repo, please update the path accordingly
autorest  --output-folder=c:\t\generated\mm1\Files.Drives  --debug  C:\git\msgraph-sdk-powershell\src\Beta\Files.Drives\Files.Drives\readme.md  --spec-doc-repo:C:/git/msgraph-sdk-powershell/openApiDocs/Beta  --title:Files.Drives  --use=@autorest/modelerfour@4.13.348  --service-name:Files.Drives
OpenAPI/Swagger file:
  swagger: https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/openApiDocs/beta/Files.Drives.yml 
  readme: https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/src/Beta/Files.Drives/Files.Drives/readme.md

![image](https://user-images.githubusercontent.com/6038235/81320171-58240700-90c3-11ea-8d92-dfcc2972bbb0.png)

**Comment by shawncx** [comment]
May I ask when this fix will be available? Some swaggers are blocked by it

**Comment by RodgeFu** [comment]
@fearthecowboy @daviwil , any idea when we can get this fixed? thanks.

**Comment by daviwil** [comment]
Sorry for the delay, looking into this now.

**Comment by daviwil** [comment]
It seems that there is legitimately a cycle in the schema graph starting from `drive`.  It goes through a lot more schemas before finally arriving back at `drive` again (but before the first occurence of `drive` has been processed completely).  I'm not sure there's a good way to handle this, but I'll talk to @fearthecowboy about it on Monday.

**Comment by daviwil** [comment]
I believe I've found a fix for this issue but I'm running into some other problems.  Will keep you posted.

**Comment by RodgeFu** [comment]
cool, thanks for the update.

**Comment by daviwil** [comment]
Hey @RodgeFu, I've sent a PR that fixes the issue, would you mind trying a test build to check it on your end?  Follow the instructions in this comment to try it:

https://github.com/Azure/autorest.modelerfour/pull/304#issuecomment-642834827

**Comment by shawncx** [comment]
Hi @daviwil , I have tried your branch, it solves the issue. Thanks!

**Comment by daviwil** [comment]
Thanks for verifying!  I've merged the fix, it's now released in `@autorest/modelerfour` 4.14.369.
