### ISSUE TITLE
FATAL: Error: Unrecognized schema type:'integer' / format: Int32 (LRO)

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.modelerfour#29]
Crash of modelerfour

**Comment by fearthecowboy** [comment]
Fixed in https://github.com/Azure/autorest.modelerfour/commit/c56e82b73fb71cc103ed2e58e18ff4284a319728

**Comment by iscai-msft** [comment]
fixed, the LRO test doesn't fail anymore
