### ISSUE TITLE
Format: int16 is not supported by Modeler four

### ISSUE THREAD

**Issue by shawncx** [Azure/autorest.modelerfour#299]
**Describe the issue**
we hit following error when trying the new codegen for MSGraph, modelerfour throw error "
ERROR (Modeler): Integer schema 'type·for·disc' with unknown format: 'int16' is not valid".

** REQUIRED ** 
**ModelerFour** version: 4.13.531
**AutoRest-core** version: 3.0.6271
**CommandLine** : autorest D:\CodeGen\msgraph-sdk-powershell\src\Beta\Files.Shares\Files.Shares\readme.md --output-folder=D:\CodeGen\output\msgraph\   --spec-doc-repo:D:\CodeGen\msgraph-sdk-powershell\openApiDocs\Beta --service-name:Files.Shares --debug  --use=@autorest/modelerfour@4.13.351
OpenAPI/Swagger file: https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/openApiDocs/beta/Files.Shares.yml
Readme: https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/src/Beta/Files.Shares/Files.Shares/readme.md

![Capture](https://user-images.githubusercontent.com/7960665/82530475-f7d79f80-9b6f-11ea-9fbe-25b6828f648f.PNG)

**Comment by RodgeFu** [comment]
@fearthecowboy @daviwil , please help to trigae, this is needed for codegen for MSGraph, thanks.

**Comment by RodgeFu** [comment]
@fearthecowboy , @daviwil , could you help to triage? thanks.

**Comment by daviwil** [comment]
Apologies for the delay, I'll take a look at this tomorrow.

**Comment by daviwil** [comment]
It appears that `int16` is not a valid format for the `integer` type according to the OpenAPI v3 specification:

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#dataTypeFormat

I'm inclined to say that this is an unsupported scenario.  Is it possible that this OpenAPI document was specified incorrectly?

**Comment by RodgeFu** [comment]
@shawncx , could you help to check with MSGraph team on this? thanks.

**Comment by darrelmiller** [comment]
@daviwil Unrecognized formats should be ignored.

> However, to support documentation needs, the format property is an open string-valued property, and can have any value. Formats such as "email", "uuid", **and so on, MAY be used even though undefined by this specification**

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#data-types

**Comment by daviwil** [comment]
@darrelmiller Thanks for the clarification!  I'll update the code to treat any unexpected integer `format` (like `int16`) as a default `integer`.

**Comment by daviwil** [comment]
Hi @shawncx, please try `@autorest/modelerfour@4.14.366`, it should resolve the issue for you.

**Comment by RodgeFu** [comment]
@shawncx , please help to verify and confirm. Thanks.

**Comment by daviwil** [comment]
Hey @shawncx, could you let me know if this fix worked for you?  Thanks!

**Comment by shawncx** [comment]
Hi @daviwil , it works prefect. Thanks

**Comment by daviwil** [comment]
Thanks for verifying @shawncx!
