### ISSUE TITLE
Error generating keyvault v7.0 (getting Data does not match any schemas from 'oneOf'

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest.modelerfour#307]
**Describe the issue**
When generating keyvault v7.0 [swagger](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.0/keyvault.json) I get this error:
![image](https://user-images.githubusercontent.com/43154838/84518913-64414c80-ac9f-11ea-931a-89357e53371d.png) . I've checked and can generate it with the older version of autorest, and I'm not seeing any `'type': 'object` definitions in body parameters. Finally, I remember being able to generate keyvault before (with this swagger version). I can't remember if I did it since the latest change to v7.0 2 months ago, but all that change did was change a required variable and that shouldn't have introduced this error

** REQUIRED ** 
**ModelerFour** version: 4.13.351
**AutoRest-core** version: 3.0.6282
**CommandLine** : autorest ../azure-rest-api-specs/specification/keyvault/data-plane/readme.md --python --use=. --multiapi --python-sdks-folder=generated
OpenAPI/Swagger file: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.0/keyvault.json

**Comment by daviwil** [comment]
@iscai-msft and I tracked this down to a [change in the KeyVault 7.0 schema](https://github.com/Azure/azure-rest-api-specs/commit/31587d1257192ea12a767edb86d84aa2d01bef8f) which resulted in an invalid Swagger that failed schema validation in the AutoRest pipeline (even in AutoRest v2).  Isabella created a PR in the specs repo to fix the issue: https://github.com/Azure/azure-rest-api-specs/pull/9860
