### ISSUE TITLE
"PLUGIN FAILURE: RECURSING!" in 4.14.369

### ISSUE THREAD

**Issue by changlong-liu** [Azure/autorest.modelerfour#313]
Hi, would you have a look at this "PLUGIN FAILURE: RECURSING!" issue in modelerfour?  I can reproduce this with modelerfour 4.14.369. 
![image](https://user-images.githubusercontent.com/59815250/86423182-c37c0500-bd11-11ea-8781-4d50e5cf8f26.png)

The swagger I test in here: https://github.com/changlong-liu/azure-rest-api-specs-pr/tree/compute-cloud-services/specification/compute/resource-manager
And my repro command is:
~~~
autorest --version=3.0.6271 --use=@autorest/modelerfour@4.14.369 c:\zz\projects\codegen\azure-rest-api-specs-pr\specification\compute\resource-manager\readme.md  --debug
~~~

**Comment by daviwil** [comment]
Apologies for the delay, I've been able to reproduce this issue and I'll investigate it in depth tomorrow morning.

**Comment by daviwil** [comment]
I believe there's a bug in the Swagger, the `JToken` definition has a recursive reference:

```
        "JToken": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/JToken"
            }
        },
```

My guess is that this was not intentional and the Swagger must be getting generated using Swashbuckle or some other tool.  You might need to see if you can exclude this type somehow or find another way to express it in your spec.

**Comment by changlong-liu** [comment]
Hi @daviwil , thank you, this looks like a swagger issue.

Is it possible that modelerfour can print out which object is RECURSING for this kind of issue? Then we can know immediately what's wrong in swagger.

**Comment by daviwil** [comment]
Yep, I've submitted PR https://github.com/Azure/autorest.modelerfour/pull/317 to make it return the schema name more reliably, it's how I discovered the schema that caused this error.

I'll close this issue for now, if you continue to see the same issue after fixing the spec I'll be happy to reopen it.  Thanks!

**Comment by changlong-liu** [comment]
That'll be very helpful. Thank you @daviwil
