### ISSUE TITLE
ServerVariable makes extra empty variable

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.modelerfour#32]
I only noticed this issue because `schema` in ServerVariable is marked as required. So, I look at my diff:
![image](https://user-images.githubusercontent.com/17788297/66443972-26947180-e9f6-11e9-8310-6bca256d139b.png)

You'll see there is a second ServerVariable with no information in it. You can see how my serialization wrote `schema` because it is required. However, why is this ServerVariable there? I look at the swagger:
https://github.com/Azure/azure-rest-api-specs/blob/420f1ad8e0b374dcbae1de895732c517d5ff9523/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.0/keyvault.json#L8-L22
```json
  "x-ms-parameterized-host": {
    "hostTemplate": "{vaultBaseUrl}",
    "useSchemePrefix": false,
    "positionInOperation": "first",
    "parameters": [
      {
        "name": "vaultBaseUrl",
        "description": "The vault name, for example https://myvault.vault.azure.net.",
        "required": true,
        "type": "string",
        "in": "path",
        "x-ms-skip-url-encoding": true
      }
    ]
  },
```

How did that get turned into 2 ServerVariables? Looks like something is buggered up.

**Comment by fearthecowboy** [comment]
Fixed in https://github.com/Azure/autorest.modelerfour/commit/3002ff426a8eed6c2fc512a4507b4481c539f8a1

**Comment by MiYanni** [comment]
@fearthecowboy The duplicate `ServerVariable` is fixed. However, the `language.default` node is an empty object, and `language` itself has `name` and `description` marked as `required`. So, it isn't valid to have those absent.
![image](https://user-images.githubusercontent.com/17788297/68522295-b4b28080-025e-11ea-92dc-c14126efd692.png)

**Comment by fearthecowboy** [comment]
Removed the server variables entirely, switched to using parameters for all server info.
