### ISSUE TITLE
Syntesise a constant Accept header based on produces swagger value

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest.modelerfour#324]

**Comment by daviwil** [comment]
I've been trying to implement this issue today and it seems I'm going to have to aggregate the media types of all responses for an operation to synthesize an `Accept` header that works for all of them.  The big question is whether I should exclude any responses that aren't in the `2xx` range or if all responses are fair game (including exceptions).  What do you think?

**Comment by pakrym** [comment]
I would've added all of them, technically the client does accept all of them.

**Comment by daviwil** [comment]
This is now out in m4 4.15.410, let me know once you've had a chance to try it and I'll close this issue.  Thanks!
