### ISSUE TITLE
Add an option to model all `x-ms-enum` as SealedChoiceSchema

### ISSUE THREAD

**Issue by daviwil** [Azure/autorest.modelerfour#329]
As @dolauli was trying to migrate `autorest.powershell` from `remodeler` to `modelerfour`, he noticed that there is a difference with how `x-ms-enum`s are handled.  In `remodeler` they are always modeled as `SealedChoice` but in `modelerfour` they can be modeled as `ConstantSchema`, `ChoiceSchema`, or `SealedChoiceSchema` based on a few different checks.

To help smooth the migration, we wil add a modelerfour option called `modelerfour.always-seal-x-ms-enums` which will created a `SealedChoiceSchema` any time an `x-ms-enum` is encountered.

**Comment by pakrym** [comment]
Would help up address https://github.com/Azure/autorest.csharp/issues/782

**Comment by daviwil** [comment]
Resolved by #334.
