### ISSUE TITLE
Promote `x-ms-text` to a property of `XmlSerializationFormat`

### ISSUE THREAD

**Issue by daviwil** [Azure/autorest.modelerfour#330]
@pakrym requested that `x-ms-text` be lifted out of the `extensions` sub-object of `XmlSerializationFormat` so that it can be a well defined part of the CodeModel schema.  This issue tracks the discussion around that work.

**Comment by daviwil** [comment]
While investigating this, it occurred to me that it's probably better to create a legimitate property for this in the `XmlSerializationFormat` type, but doing that might require rethinking things slightly.  Now that we will have both `attribute` and `text` as properties of this type, we need to ensure that they are mutually exclusive since the same property can't take it's value from both places at the same time.

A better way to do this would be to have a new field like `location` that uses an enum to determine whether the property can be found in an attribute or the text of the node.  However, this would require all code generators to adjust to `attribute` being removed (or deprecated and still populated with `true` if it location is `attribute`).

Thoughts?  @pakrym @lmazuel

**Comment by lmazuel** [comment]
I think it's overkill, and I'm happy with attribute and text being two separate boolean entitites :)

**Comment by pakrym** [comment]
Yeah, I'm fine with two attributes and maybe an error if both are set.

**Comment by lmazuel** [comment]
I would not expect any generator to have to check the mutex part of attribute/text, but to assume this was done correctly, and let m4 fail if it was not.

**Comment by daviwil** [comment]
OK, I can add extra logic to modelerfour to fail if both properties are `true` so that it never makes it to the generator and the user gets a reasonable error message.  Thanks for the feedback!

**Comment by daviwil** [comment]
This was fixed in https://github.com/Azure/autorest.modelerfour/pull/332.
