### ISSUE TITLE
Response with string body being treated as empty response

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest.modelerfour#352]
**Describe the issue**
The [string response object](https://github.com/Azure/azure-rest-api-specs/blob/1e23d91e875e4464e57667639e06408cef99868d/specification/schemaregistry/data-plane/Microsoft.EventHub/preview/2020-09-01-preview/schemaregistry.json#L96) in the schema registry swagger is being generated as having no body. The response headers are being generated correctly

![image](https://user-images.githubusercontent.com/43154838/94177917-5dae9d80-fe68-11ea-9b2f-f769410faeed.png)

** REQUIRED ** 
**ModelerFour** version: 4.15.419
**AutoRest-core** version: 3.0.6320
**CommandLine** : autorest ../azure-rest-api-specs/specification/schemaregistry/data-plane/readme.md --python --v3 --python-sdks-folder=/Users/isabellacai/Desktop/github_repos/autorest.python/generated/ --output-artifact=code-model-v4-no-tags --use=.
OpenAPI/Swagger file: https://github.com/Azure/azure-rest-api-specs/blob/1e23d91e875e4464e57667639e06408cef99868d/specification/schemaregistry/data-plane/Microsoft.EventHub/preview/2020-09-01-preview/schemaregistry.json#L96

**Comment by daviwil** [comment]
Fixed in 4.15.421.  Thanks for the help verifying @iscai-msft!
