### ISSUE TITLE
Triple forward slash when using $(this-folder) as part of a --use parameter

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.modelerfour#36]
Basically, my samples in my extension all reference the same readme. I wanted to add a `use` to that readme to include the local extension itself. Therefore, I'd need `use: $(this-folder)`. Or, I wanted to keep this readme in a folder below the extension (the `samples` folder), so the value would be `use: $(this-folder)/../`. The folder itself is being resolved properly, but the path is prepended with `file:///`. The triple slashes are not a valid Windows path. So, it just fails.

![image](https://user-images.githubusercontent.com/17788297/68520586-a314ad00-024d-11ea-9580-482d2d628162.png)

**Comment by fearthecowboy** [comment]
fixed in autorest-core

**Comment by MiYanni** [comment]
Fixed!
![image](https://user-images.githubusercontent.com/17788297/68635000-0c91f700-04ac-11ea-9646-9f0986ee4090.png)
