### ISSUE TITLE
ConstantSchema serialized incorrectly

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.modelerfour#37]
Cannot deserialize any codemodels with constants currently.

Currently, `ConstantSchema` is defined to have a `Value` that is a `ConstantValue`, which has its own set of properties. However, right now, the code model is sending this as just a flat value, not an object.
![image](https://user-images.githubusercontent.com/17788297/68520857-2931f300-0250-11ea-9307-a9cc8cdb8f15.png)

So, this should be a `!<!ConstantValue>` that has a `Value` property with the value `service`.

**Comment by fearthecowboy** [comment]
I've pushed a fix to modelerfour to put a `ConstantValue` in there. 

G

**Comment by MiYanni** [comment]
Fixed.
