### ISSUE TITLE
Namespace in Language.Default is dropping duplicate numbers

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.modelerfour#38]
From `blob-service.json`'s code model:
![image](https://user-images.githubusercontent.com/17788297/68521681-4ff42780-0258-11ea-9906-617d224f49da.png)

The `apiVersion` I use in my CSharp node is created from the `apiVersions` array. I don't use the `namespace` node, but it seems to be a bug for those that use it.

**Comment by fearthecowboy** [comment]
Oh. that's freaking hilarious.

**Comment by fearthecowboy** [comment]
Fixed by #51

**Comment by MiYanni** [comment]
Fixed! 😄
