### ISSUE TITLE
TypeError: Invalid Version: 3.0-Preview.1

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.modelerfour#41]
I'm assuming we have some standard format for version numbers. But... TextAnalytics has a version number, `3.0-Preview.1`. Do we not support this?
![image](https://user-images.githubusercontent.com/17788297/68634447-5e398200-04aa-11ea-903b-8c6c1c17376d.png)

The swagger is here:
https://github.com/Azure/azure-rest-api-specs/pull/7133/files#diff-1c77f57cfc4f285d67b229e91da4cd2b

**Comment by fearthecowboy** [comment]
FOR [$%*^%#] sakes. 

That's not a semver. We (at this point) support SemVer and Date formats for api versions.

*sigh*

I don't know how people in this day and age can constantly just use arbitrary unstructured formats for versions.

**Comment by fearthecowboy** [comment]
fixed in autorest-core (`autorest-beta --reset `) -- please confirm

**Comment by MiYanni** [comment]
This issue seems fixed. However, there is another issue with this swagger. I'll open it as a new issue.
