### ISSUE TITLE
ServerVariable schema, missing information and other issues

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.modelerfour#42]
![image](https://user-images.githubusercontent.com/17788297/68731966-bd6cc480-0586-11ea-9856-90893d0c4477.png)

![image](https://user-images.githubusercontent.com/17788297/68732049-f442da80-0586-11ea-9229-c1ab37b8ed95.png)

So, few things to note:
- Missing information like correct type, required, 'in', and extensions.
- What else is ValueSchema used for? I feel like this should be a `Schema`, and remove `ValueSchema` entirely. For example, in the above, it is defined as `type: string`, so it should be a `StringSchema`.
- The schema used here should be propagated to the appropriate collection in `schemas`. It isn't anywhere other than being defined within the ServerVariable right now.
- It seems that `positionInOperation` and `useSchemePrefix` are missing in `HttpServer`.

So, I can't make calls if I can't get the correct information about the server variables, because I need to turn the server variables into parameters for my static operation methods.

**Comment by fearthecowboy** [comment]
This should be moot, having converted parameterized hosts over to path parameters.

**Comment by MiYanni** [comment]
Works well now that it is a parameter. Closing.
