### ISSUE TITLE
Property named 'null' becomes nothing in Name

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.modelerfour#48]
![image](https://user-images.githubusercontent.com/17788297/68987737-a7a70b80-07e1-11ea-8a9d-ed5d42c4f9cc.png)

This is when you run through it with: https://github.com/Azure/autorest.testserver/blob/master/swagger/body-complex.json

**Comment by fearthecowboy** [comment]
This is after your namer runs -- what does the YAML that you're serializing spit out?

When I serialize it it's there...
![image](https://user-images.githubusercontent.com/133736/69171838-8da34c80-0ab1-11ea-856c-a54edad5a6ce.png)

**Comment by MiYanni** [comment]
@fearthecowboy UGH. I'd have to implement a custom way to serialize/deserialize this. https://github.com/aaubry/YamlDotNet/issues/387
Closing.
