### ISSUE TITLE
Handle null values from Swagger/OpenApi 3.0 doc

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.modelerfour#55]
The `body-string.json` test server swagger has significant `null` values. For example:
![image](https://user-images.githubusercontent.com/17788297/69395237-2a711000-0c93-11ea-9701-a7be0d287864.png)

This value seems to be optimized out from the code model. So, when deserializing, I see no value there which is different from a `null` value. So, this needs to be preserved or else that information is missing (and I can't process it properly).

**Comment by fearthecowboy** [comment]
+ Also body-byte has an enum with a null value.

**Comment by weidongxu-microsoft** [comment]
body-datetime-rfc1123 got a similar one with single enum, which results without to `type: string`.

 ```
     "get": {
        "operationId": "datetimerfc1123_getUtcMinDateTime",
        "description": "Get min datetime value Mon, 1 Jan 0001 00:00:00 GMT",
        "responses": {
          "200": {
            "description": "The min datetime value Mon, 1 Jan 0001 00:00:00 GMT",
            "schema": {
              "type": "string",
              "format": "date-time-rfc1123",
              "enum": [
                "Sun, 1 Jan 0001 00:00:00 GMT"
              ]
            }
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
```

**Comment by fearthecowboy** [comment]
These cases are now addressed:
- constant schemas are just reduced to the schema type on response. 

Tangentially, #73 makes date constants properly handled (in this case here, it's not a constant anymore, so #73 isn't the actual fix, but it would be in a input.)

**Comment by fearthecowboy** [comment]
And we have #57 to address properly supporting `null` values.

**Comment by MiYanni** [comment]
@fearthecowboy I don't think this is fixed. According to that swagger for body-string, you'd expect that the 200 response would have a schema of ConstantSchema, where it has a ConstantValue of null. But, we get this:
![image](https://user-images.githubusercontent.com/17788297/70745507-bf868800-1cd8-11ea-874a-39097e495ff2.png)
Where ref_0 is:
![image](https://user-images.githubusercontent.com/17788297/70745586-f2308080-1cd8-11ea-8699-7b91a9cee686.png)

So, that's not right. The thing that is interesting... other operations do properly use a ConstantSchema I'd expect:
![image](https://user-images.githubusercontent.com/17788297/70745757-623f0680-1cd9-11ea-96ed-f1583434db5d.png)

Maybe it is just referencing the wrong schema for the response???

**Comment by fearthecowboy** [comment]
We no longer use constants for responses we use the type of the constant. @lmazuel

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MiYanni** [comment]
@fearthecowboy @lmazuel 
In this situation, it is a loss of data. Because, there is a defined value the server is returning, and now it isn't in the code model... I had some other ideas, but they aren't that great. Since this is uniquiely intended to be a 'constant', and we don't want constants as responses, the best thing we can do is make `"enum": [ null ]` into a SealedChoiceSchema where the only value is null. I have no idea what that would mean for C#, but logically, that is what the intent of the response being defined there. Thoughts?

**Comment by fearthecowboy** [comment]
We can't have constant return values; to do so is not good swagger.
