### ISSUE TITLE
Add case insensitive comparer for operation groups

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest.modelerfour#59]

**Comment by fearthecowboy** [comment]
#68 addresses this:

To use this version: 

Ensure that you're on `@autorest/autorest ` `3.0.6141` or greater:
``` 
npm install -g @autorest/autorest
```
and then do a `--reset` and get the specific `autorest-core` package version 3.0.6162, and the `modelerfour` `4.2.75`
``` 
autorest-beta --reset 
autorest-beta --version:3.0.6162 --use:@autorest/modelerfour@4.2.75 
```
