### ISSUE TITLE
Parameters defines inside "x-ms-parameterized-host" should be consider method level by default

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.modelerfour#60]
See:
https://github.com/Azure/autorest.testserver/blob/0b1e8a2a65915c225851333c2eebe1ff57a3e606/swagger/custom-baseUrl.json#L12-L21

At least that was the case in autorest v2:
- "host" is client level (defined in "parameters")
- "accountName" is method level (defined in "x-ms-parameterized-host/parameters")

**Comment by fearthecowboy** [comment]
O_o

Oh. ah. interesting... 

I may have to go and look at the oai2-to-oai3 upconverter works.

**Comment by fearthecowboy** [comment]
Hmmm. 

Requires a small fix in autorest-core and in modeler four. Fun stuff :D 

use core `3.0.6163` and modelerfour `4.2.77` :

`autorest-beta --version:3.0.6163 --use:@autorest/modelerfour@4.2.75 `
