### ISSUE TITLE
Drop constant if applied to response

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.modelerfour#63]
As discussed on teams, if the response is a constant, drop it

**Comment by lmazuel** [comment]
https://github.com/Azure/autorest.testserver/blob/0b1e8a2a65915c225851333c2eebe1ff57a3e606/swagger/body-date.json#L184-L186
https://github.com/Azure/autorest.testserver/blob/0b1e8a2a65915c225851333c2eebe1ff57a3e606/swagger/body-byte.json#L41
https://github.com/Azure/autorest.testserver/blob/0b1e8a2a65915c225851333c2eebe1ff57a3e606/swagger/body-datetime.json#L341

**Comment by fearthecowboy** [comment]
#68 addresses this:

To use this version: 

Ensure that you're on `@autorest/autorest ` `3.0.6141` or greater:
``` 
npm install -g @autorest/autorest
```
and then do a `--reset` and get the specific `autorest-core` package version 3.0.6162, and the `modelerfour` `4.2.75`
``` 
autorest-beta --reset 
autorest-beta --version:3.0.6162 --use:@autorest/modelerfour@4.2.75 
```

**Comment by lmazuel** [comment]
@fearthecowboy I still have type trouble, for instance:
https://github.com/Azure/autorest.testserver/blob/0b1e8a2a65915c225851333c2eebe1ff57a3e606/swagger/body-date.json#L184-L186

I don't get a date but a string. Related to https://github.com/Azure/autorest.modelerfour/issues/70 ?

**Comment by lmazuel** [comment]
I think this issue itself is fixed, and I just moved trhough the date one.
