### ISSUE TITLE
Collection format is missing in code model

### ISSUE THREAD

**Issue by jianghaolu** [Azure/autorest.modelerfour#66]
Spec at https://github.com/Azure/autorest.testserver/blob/master/swagger/url.json#L760

```
    "/paths/array/ArrayPath1%2cbegin%21%2A%27%28%29%3B%3A%40%20%26%3D%2B%24%2C%2F%3F%23%5B%5Dend%2c%2c/{arrayPath}": {
      "get": {
        "operationId": "paths_ArrayCsvInPath",
        "description": "Get an array of string ['ArrayPath1', 'begin!*'();:@ &=+$,/?#[]end' , null, ''] using the csv-array format",
        "tags": [
          "query Operations"
        ],
        "parameters": [
          {
            "name": "arrayPath",
            "in": "path",
            "required": true,
            "description": "an array of string ['ArrayPath1', 'begin!*'();:@ &=+$,/?#[]end' , null, ''] using the csv-array format",
            "type": "array",
            "items": {
              "type": "string"
            },
            "collectionFormat": "csv"
          }
        ],
```

generated code model with no `csv` anywhere to be found. This prevents url tests being generated and tested.

**Comment by fearthecowboy** [comment]
In OAI3 (which we upconvert to) has a `style` that goes along with the parameter 

the supported formats:

[`style`](#dataTypeFormat) | `explode` | `empty` | `string` | `array` | `object`
----------- | ------ | -------- | -------- | --------|-------
matrix | false | ;color | ;color=blue | ;color=blue,black,brown | ;color=R,100,G,200,B,150
matrix | true | ;color | ;color=blue | ;color=blue;color=black;color=brown | ;R=100;G=200;B=150
label | false | .  | .blue |  .blue.black.brown | .R.100.G.200.B.150
label | true | . | .blue |  .blue.black.brown | .R=100.G=200.B=150
form | false | color= | color=blue | color=blue,black,brown | color=R,100,G,200,B,150
form | true | color= | color=blue | color=blue&color=black&color=brown | R=100&G=200&B=150
simple | false | n/a | blue | blue,black,brown | R,100,G,200,B,150
simple | true | n/a | blue | blue,black,brown | R=100,G=200,B=150
spaceDelimited | false | n/a | n/a | blue%20black%20brown | R%20100%20G%20200%20B%20150
pipeDelimited | false | n/a | n/a | blue\|black\|brown | R\|100\|G\|200|G\|150
deepObject | true | n/a | n/a | n/a | color[R]=100&color[G]=200&color[B]=150

OAI3 doesn't have tab delimited, but I've added a `tabDelimited` in the model to support that. 

I will add this style to the parameter in the code model

**Comment by fearthecowboy** [comment]
#69 addresses this:
To use this version: 

Ensure that you're on `@autorest/autorest ` `3.0.6141` or greater:
``` 
npm install -g @autorest/autorest
```
and then do a `--reset` and get the specific `autorest-core` package version 3.0.6162, and the `modelerfour` `4.2.75`
``` 
autorest-beta --reset 
autorest-beta --version:3.0.6162 --use:@autorest/modelerfour@4.2.75 
```

**Comment by lmazuel** [comment]
I see it indeed now
![image](https://user-images.githubusercontent.com/1050156/70554946-f9b62500-1b32-11ea-9b23-1f7d7acf2eec.png)

**Comment by lmazuel** [comment]
@fearthecowboy found one missing:
https://github.com/Azure/autorest.testserver/blob/e0d8dcad0f06f45ad6ec4416e45b326a139a63ff/swagger/url-multi-collectionFormat.json#L63

CodeModel:
![image](https://user-images.githubusercontent.com/1050156/70558285-7ba94c80-1b39-11ea-90ef-ea9ba986cee6.png)

**Comment by lmazuel** [comment]
Note that's the only one I found missing so far, I fixed several bugs already :)

**Comment by jianghaolu** [comment]
Seems to have everything I need now in the code model - is this still an issue for you @lmazuel ?

**Comment by lmazuel** [comment]
nope fine
