### ISSUE TITLE
Not getting operation summaries

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest.modelerfour#77]
We're getting descriptions but not summaries of operations. See https://github.com/Azure/azure-rest-api-specs/blob/ef354ec8d6580227707ed935684e533b898beabe/specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.0-preview.1/TextAnalytics.json#L37

**Comment by fearthecowboy** [comment]
Interesting, we actually have usage of summaries. 
I'll Take a look

**Comment by lmazuel** [comment]
Example in testserver:
https://github.com/Azure/autorest.testserver/blob/2368e0730489645590a98765faaea3dbc68d7e29/swagger/body-datetime.json#L134-L135

**Comment by lmazuel** [comment]
Pushing that to P0 since we fixed most of our P0 to prioritized the P1 I found important

**Comment by fearthecowboy** [comment]
Ah, I fixed a while ago. (see `language.default.summary` -- will be there if a summary is present. )
https://github.com/Azure/autorest.modelerfour/blob/master/modelerfour/test/scenarios/text-analytics/modeler.yaml#L2331

**Comment by fearthecowboy** [comment]
This got fixed a while ago. Try it out with a recent build .

**Comment by fearthecowboy** [comment]
Summary will be in `language.default.summary` when it's present.

**Comment by lmazuel** [comment]
@iscai-msft cold you try to integrate it?

**Comment by iscai-msft** [comment]
yep, it's all good now, thanks @fearthecowboy !
