### ISSUE TITLE
Examples are missing

### ISSUE THREAD

**Issue by zikalino** [Azure/autorest.modelerfour#79]
There are no examples included in codemodel-v4.

This is probably autorest-beta issue as well, as when using autorest-beta to produce codemodel-v1 I am also ending up with codemodel-v1 without examples, but I am creating it here as well as most likely in needs some handling in both places.

**Comment by zikalino** [comment]
Pls add "Critical" label if possible, as this is really high priority for us.

**Comment by fearthecowboy** [comment]
I've got the loader pulling the data into the OAI3 document

It's going to take me a few more days; preserving the information thru merging multiple api versions is tricky.

**Comment by fearthecowboy** [comment]
I have updated the OAI2-to-OAI3 converter to pull in the examples, so I’ll have them in the OAI3 doc by the time it reaches the modeler. 

I’ve published prerelease versions – give this a try:

-	install the prerelase autorest-beta:
> `npm install -g https://github.com/Azure/autorest/releases/download/autorest-3.0.6149/autorest-autorest-3.0.6149.tgz `
-	reset plugins: 
> `autorest-beta --reset `
-	use pre-release autorest-core 3.0.6174:
> `autorest-beta --version:3.0.6174 …`

x-ms-* extension data that is in the OAI3 doc is propagated to the model (iirc even in remodeler *I think*) , so you should start seeing the data show up in the new version.

Hopefully this will give you something to play with now.

## CAVEATS:
-	I’m worried that there are going to be conflicts when multiple API versions are merged, and I haven’t quite figured out what that will look like yet.
-	I may have to refactor how that data shows up in merged models, I can’t guarantee I won’t break something in the not-too-distant future.

**Comment by lmazuel** [comment]
I confirmed it's there, it even broke me :)
