### ISSUE TITLE
$host should have a serializedName

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.modelerfour#80]
![image](https://user-images.githubusercontent.com/1050156/70561984-62f06500-1b40-11ea-917a-26c897a0133a.png)

**Comment by fearthecowboy** [comment]
Should be in modelerfour `2.4.92`+  (`--use:@autorest/modelerfour@2.4.92`) 

(example: https://github.com/Azure/autorest.modelerfour/blob/master/modelerfour/test/scenarios/body-byte/modeler.yaml#L138 )

**Comment by lmazuel** [comment]
fixed
