### ISSUE TITLE
"ApiVersion" should have implementation Method

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.modelerfour#81]
Right now it's not the case. Even if this one is special, still I believe it should be present there,

> AutoRest code generation utility [version: 3.0.6146; node: v10.15.3, max-memory: 8192 gb]
>  core       @autorest/core                           3.0.6169     C:\Users\lmazuel\.autorest\@autorest_core@3.0.6169
>  extension  @autorest/modelerfour                    4.2.84       C:\Users\lmazuel\.autorest\@autorest_modelerfour@4.2.84

**Comment by lmazuel** [comment]
Re-phrase after discussing with Garrett

**Comment by fearthecowboy** [comment]
Can we close this @lmazuel ?
