### ISSUE TITLE
Global parameters wrong order

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.modelerfour#82]
Order of global parameters should be respected. Example here:
https://github.com/Azure/autorest.testserver/blob/e0d8dcad0f06f45ad6ec4416e45b326a139a63ff/swagger/custom-baseUrl-more-options.json#L77-L94

"subscriptionId" is before "dnsSuffix"

However, the modeler give them to me backward:
![image](https://user-images.githubusercontent.com/1050156/70567745-62110080-1b4b-11ea-9dc6-dfb1c99a3c49.png)

**Comment by fearthecowboy** [comment]
Oh.

Uh...

This is trickier than it appears.  

I think I'm going to have to add an ordering hint in the OAI3 doc, and somehow sort the parameters array based on that. 

😢

**Comment by fearthecowboy** [comment]
Fix is in -- you're going to need to grab update to `autorest-core` `3.0.6174` and  modelerfour `4.2.92`

> `autorest-beta --version:3.0.6174 --use:@autorest/modelerfour@4.2.92 ... `  

- the OAI2-to-OAI3 converter adds information in to allow server/variables to connect to the original referenced parameter 
- modelerfour tags each original global parameter (that was specified in the parameters section in the original spec) with a priority in the order in which it's listed. (this adds significance to the order of things in a *technically* unordered map, but we'll go with it)
- when a global parameter is added to the code model, it sorts the array based on the priority if it has one attached. Additional global parameters that are manufactured are added at the end.
- the global parameters keep an `x-ms-priority`  in their `extensions` -- this may be of some marginal value to you, if you wanted to know which parameters were globally defined originally, as they will have a value and ones that were not in the global list will not.

**Comment by fearthecowboy** [comment]
You should now see them reordered: https://github.com/Azure/autorest.modelerfour/blob/master/modelerfour/test/scenarios/custom-baseUrl-more-options/modeler.yaml#L91

**Comment by lmazuel** [comment]
fixed
