### ISSUE TITLE
Not supporting x-ms-client-name

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest.modelerfour#88]
See for an example: https://github.com/Azure/azure-rest-api-specs/blob/28adfecc8c8d9a425451a5b7f6f2688e471a60f4/specification/keyvault/data-plane/Microsoft.KeyVault/preview/7.0/keyvault.json#L5082

**Comment by iscai-msft** [comment]
Here's what we're getting in the yaml:
![image](https://user-images.githubusercontent.com/43154838/70761074-d04af400-1d00-11ea-99c9-c1ea41a85e1b.png)

**Comment by lmazuel** [comment]
Blocks https://github.com/Azure/autorest.python/issues/246

**Comment by fearthecowboy** [comment]
Just published: `--use:@autorest/modelerfour@4.2.95`

**Comment by fearthecowboy** [comment]
https://github.com/Azure/autorest.modelerfour/blob/06048867e82a5a14eb0a0e2cb0f918c0c05b6519/modelerfour/test/scenarios/keyvault/modeler.yaml#L226
