### ISSUE TITLE
ApiVersion parameter doesn't have validation constraints

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.modelerfour#90]
Example this:
https://github.com/Azure/autorest.testserver/blob/8637caf554416717f071e0b4f8a39768d5ea2d83/swagger/validation.json#L286

Is missing from the model

**Comment by fearthecowboy** [comment]
O_o

This is a strange case; it's called an apiversion parameter, but it doesn't actually need to be treated like the modeler does for Azure api version parameters (where we manage how they're handled)

The trouble is... how to identify this vs ones we're using in ARM. 

(thinking....)

**Comment by fearthecowboy** [comment]
can we close this?
