### ISSUE TITLE
Missing skip encoding metata

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.modelerfour#92]
See:
https://github.com/Azure/autorest.testserver/blob/a5e6e2ef725df87c8981116836531a2f10be9128/swagger/azure-special-properties.json#L621-L630

M4:
![image](https://user-images.githubusercontent.com/1050156/70938389-ef949a80-1ffa-11ea-97cb-cf423ca90189.png)

M4 4.2.99, Core 3.0.6179, CMD 3.0.6149

**Comment by fearthecowboy** [comment]
Fixed in 4.2.106 

![image](https://user-images.githubusercontent.com/133736/72278972-f4447280-35e9-11ea-8e25-e3486b11ea70.png)

**Comment by lmazuel** [comment]
Indeed, thanks!!

**Comment by lmazuel** [comment]
Actually, I mixed up with another issue, but let me check right now

**Comment by lmazuel** [comment]
Fixed indeed:
https://github.com/Azure/autorest.python/pull/303
