### ISSUE TITLE
If nextLinkName is null in Swagger, it's {} in model from m4

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.modelerfour#95]
Testserver 2.7.8
https://github.com/Azure/autorest.testserver/blob/1a10b5324156680680d040aa6124568a59dd96cb/swagger/paging.json#L39

![image](https://user-images.githubusercontent.com/1050156/71022618-c422b600-20b5-11ea-8dac-c87ac608f85c.png)

I think we should get `null` here, not empty dict.

**Comment by fearthecowboy** [comment]
Fixed in 4.6+

**Comment by lmazuel** [comment]
Fixed part of the paging refactoring
