### ISSUE TITLE
x-ms-client-name failing for some keyvault code

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest.modelerfour#96]
There are still problems in x-ms-client-name. Here are some of the issues I found in KeyVault (there are probably more issues)
https://github.com/Azure/autorest.python/issues/252

This is the swagger I'm using: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.0/keyvault.json

**Comment by fearthecowboy** [comment]
Try `--version:3.0.6181`  and `--use:@autorest/modelerfour@4.2.102` 

inlined enums with x-ms-client-name should be picking up the property correctly. 

https://github.com/Azure/autorest.modelerfour/blob/master/modelerfour/test/scenarios/keyvault/namer.yaml#L1374
