### ISSUE TITLE
Consider a more targeted alternative for payload-flattening-threshold

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest.modelerfour#99]
Having a global setting like `payload-flattening-threshold` is a breaking change waiting to happen because seemingly safe addition of parameter would result in massive API change.

There is also no way to opt-out on method level.

I propose having a request parameter attribute that would make only that attribute flattened.

We should also encourage swaggers to migrate off the `payload-flattening-threshold` to the new attribute to improve future API stability.

**Comment by fearthecowboy** [comment]
You can set `x-ms-payload-flattening-threshold` on an operation to have fine-grained control for the threshold value (ie, `x-ms-payload-flattening-threshold: 4` )

**Comment by pakrym** [comment]
What about being able to set something like `x-ms-flatten` on parameters themselves?

**Comment by fearthecowboy** [comment]
`x-ms-client-flatten: true` on the body parameter can accomplish that (and conversely, `x-ms-client-flatten: false` on the parameter will explicitly prohibit the threshold from applying)

**Comment by pakrym** [comment]
Can m4 process `x-ms-payload-flattening-threshold` and set `x-ms-client-flatten` on parameters so generators don't have to handle 2 things?
